### ISSUE TITLE
Call to undefined function App\Http\Controllers\Setup\alert()

### ISSUE THREAD

**Issue by Kovah** [Kovah/LinkAce#106]
```php
public function configure(SetupDatabaseRequest $request)
{
    $this->createTempDatabaseConnection($request->all());
 
    if ($this->databaseHasData() && !$request->has('overwrite_data')) {
        alert(trans('setup.database.data_present'), 'danger'); // issue with that function?
        return redirect()->back()->with('data_present', true)->withInput();
    }

    // ...
}
```

_Submitted by N. Travassos via email_

**Comment by nicotravassos** [comment]
@Kovah perhaps just test this on your side. Maybe my copy of this repository has gone bonkers.

**Comment by Kovah** [comment]
Will test this as soon as possible. Should not happen, but maybe I overlooked something. Di not test the setup with data in the database very extensively. 😬

**Comment by nicotravassos** [comment]
👍 Keep me posted @Kovah

**Comment by Kovah** [comment]
Couldn't reproduce the issue. Tested this with an empty and full database, the alert works correctly.

Could you solve it on your server? If not please post some more information, perhaps it's related to a specific environment?

**Comment by nicotravassos** [comment]
@Kovah  interesting I shall test again. Any chance it is because I am using PostgreSQL instead of MySQL?

**Comment by nicotravassos** [comment]
Any chance you can try using PostgreSQL?

**Comment by Kovah** [comment]
I will test this. Possible that it may cause issues.

**Comment by nicotravassos** [comment]
Please do let me know.  I also noticed if the data exists and password for DB is set within `.env` if you press proceed it will throw that alert error and duplicate the password so `DB_PASSWORD=1234` will become `DB_PASSWORD=12341234`

**Comment by Kovah** [comment]
Thanks for the information, will take a look at it.
