### ISSUE TITLE
Duplicates finder

### ISSUE THREAD

**Issue by newpdv** [Kovah/LinkAce#112]
A good function is to search for duplicate links, both when adding a link, and after import.

P.S. All garbage from URL (protocol, www, trailing slashes, useless query parameters or hash strings) should be ignored.

**Comment by Kovah** [comment]
Sounds good, maybe this could be integrated into the regular link checks.

**Comment by Kovah** [comment]
I am currently thinking about the actual implementation.

My first idea of integrating it into the regular link checks, but there are some flaws. As the current link checks are mean to check the accessibility of resources, the duplicate check maintains database consistency. Putting both into the same boat does not seem to fit. Also, getting information about duplicate links each once in a while when links are checked seem annoying.

Having the checks available as a search feature does not seem to fit too. Having to run it manually is tedious and not a straight forward help to reduce duplicates.

My current best bet would be to integrate this feature into the link creation process. After saving a link, we could run an additional check for duplicates. If some are found, they are pushed to the frontend with a notification.

@newpdv What do you think?

**Comment by newpdv** [comment]
Hello! I think a forced link check is not needed if we keep the database up to date, checking all links when adding or importing. And additional check when changing link.
