### ISSUE TITLE
Import exception: "Undefined variable: time"

### ISSUE THREAD

**Issue by newpdv** [Kovah/LinkAce#114]
This call throws an error: "Undefined variable: time"
https://github.com/Kovah/LinkAce/blob/3987f5ddbf4bb9bc46a9c388f49307a21dbb85b9/app/Http/Controllers/App/ImportController.php#L46

because in this commit, the author replaced the time() with an $time variable

https://github.com/shaarli/netscape-bookmark-parser/commit/78b316f1a0154873e9621889ba495e607896eb28#diff-4a59dbd62a2dae2500f43e35fb7d51ceR232

**Comment by Kovah** [comment]
Will take a look at it.

**Comment by Kovah** [comment]
Could you share a sample file that causes the error? I tried the import with a recent export of my browser bookmarks and it ran just fine.

**Comment by newpdv** [comment]
Please try with that file: https://github.com/shaarli/netscape-bookmark-parser/blob/master/NetscapeBookmarkParser.php
maybe this error depends on the server or laravel configuration?
unknown variable should not cause fatal error...

**Comment by newpdv** [comment]
it definitely doesn't depend on APP_ENV / APP_DEBUG variables

**Comment by newpdv** [comment]
PHP 7.4.5

**Comment by Kovah** [comment]
I double checked this, it's the current installed version, the file hashes match.

Could you share the bookmarks file you are trying to import? Maybe there's something wrong with the formatting.

**Comment by newpdv** [comment]
> I double checked this, it's the current installed version, the file hashes match.
> 
> Could you share the bookmarks file you are trying to import? Maybe there's something wrong with the formatting.

Try this test file [test_bug_file.html.zip](https://github.com/Kovah/LinkAce/files/4548901/test_bug_file.html.zip)

**Comment by newpdv** [comment]
Reference https://github.com/shaarli/netscape-bookmark-parser/issues/49

**Comment by Kovah** [comment]
Okay, I will push this out of 0.0.35, as this is actually an internal bug with the Bookmark Parser. A fork might be needed here because it seems unlikely that this issue will be fixed soon with a new release.

**Comment by Kovah** [comment]
Issue should be fixed in latest 2.2.0 release of the parser.

**Comment by Kovah** [comment]
This might be solved with the next release, as the Bookmark Parser library was updated.

**Comment by Kovah** [comment]
Tested this with the provided export file, works without issues.
