### ISSUE TITLE
Add link with unavailable port / host

### ISSUE THREAD

**Issue by newpdv** [Kovah/LinkAce#115]
If you add a link with an unavailable port (for example http://127.0.0.1:11111), it will throw an error: "cURL error 7: Failed to connect to 127.0.0.1 port 11111: Connection refused"

**Comment by newpdv** [comment]
the same if the domain is unavailable: "cURL error 6: Could not resolve host

**Comment by Kovah** [comment]
Will also take a look into this.
Thanks for your feedback and ideas! 😊
