### ISSUE TITLE
Sites with non-UTF encoding cause a database error

### ISSUE THREAD

**Issue by newpdv** [Kovah/LinkAce#119]
If the site uses an outdated encoding (for example, windows-1251), this will cause a database error due to encoding mismatch:
> SQLSTATE[HY000]: General error: 1366 Incorrect string value for column 'description' at row 1

https://github.com/Kovah/LinkAce/blob/master/app/Http/Controllers/App/ImportController.php#L71

**Comment by Kovah** [comment]
Do you have an example site at hand that I might use for testing this?

**Comment by newpdv** [comment]
Sure, https://pikabu.ru

**Comment by Kovah** [comment]
I did not expect this to be that complicated, but I think the solution is pretty good.

LinkAce now checks the `charset` meta tag. If it's present and not UTF-8, the app will try to convert the meta from the original encoding to UTF-8.

If no `charset` tag is present, it will additionally check if the title is not encoded as UTF-8. If that's the case, no meta will be passed and the domain is used as the title. Trying to detect the encoding and correctly convert it without any information is almost impossible. I tried various encodings and all returned garbage. Besides that, websites [should always have a charset tag](https://www.w3.org/International/questions/qa-html-encoding-declarations).

**Comment by newpdv** [comment]
I think you will be interested to know that the vast majority of sites use **UTF-8**, but also a small number use **Windows-1251** and **ISO-8859-1** (for example https://www.mediafire.com)

![encoding stats](https://user-images.githubusercontent.com/2841429/80764723-f6572080-8b49-11ea-8f73-37b838c29da9.png)
