### ISSUE TITLE
You forgot to change the version to 0.0.39

### ISSUE THREAD

**Issue by FanyangMengDev** [Kovah/LinkAce#138]
Please have a check
https://github.com/Kovah/LinkAce/blob/7d270b9e3014ad289e87c1fdb95c7fbd4c8c2c0e/config/linkace.php#L3

**Comment by Kovah** [comment]
Yes, I really did. It's a pain. I already change the way the version is checked and displayed in the app.
Thanks for the heads up, will leave this for the few days until the next version.
