### ISSUE TITLE
I wanna offer some help with Chinese translation

### ISSUE THREAD

**Issue by MFYDev** [Kovah/LinkAce#139]
Hi Kovah,

Have you ever taken into account that adding Chinese translation?

When you wanna add other translations, I wanna offer some help. : )

**Comment by Kovah** [comment]
Hi!
Thank you very much for the offer. Translations can already be submitted via our Crowdin project. More details in the docs: https://www.linkace.org/docs/v1/general/translations

**Comment by FanyangMengDev** [comment]
Done. Just translated all files into Chinese Simplified.

Hoping we can use this translation in the next version.

Thank you for your perfect project and hard working! : )

**Comment by FanyangMengDev** [comment]
![image](https://user-images.githubusercontent.com/53750381/90051203-eb478b00-dd09-11ea-9d6f-2b33a41ac601.png)

![image](https://user-images.githubusercontent.com/53750381/90051210-ee427b80-dd09-11ea-8423-b4e724f05171.png)

**Comment by FanyangMengDev** [comment]
I will share LinkAce to the people around me. This perfect bookmark tool can help us cross different browsers and platforms.

**Comment by Kovah** [comment]
Thank you very much! will will include them in the next release.

**Comment by Kovah** [comment]
Including translations into releases will be done in a later version until all final language strings are defined and properly translated.

**Comment by FanyangMengDev** [comment]
![image](https://user-images.githubusercontent.com/53750381/92396081-fe0d7e00-f156-11ea-9685-f99e086a330f.png)

Hi Kovah, all things have been translated and I do not know why Crowdin still display 99%? Could you please have a check?

**Comment by FanyangMengDev** [comment]
![image](https://user-images.githubusercontent.com/53750381/92396248-4af15480-f157-11ea-84f3-09ee6da89baa.png)
Done. All things have been translated into Chinese. Would you please add this to the milestone again?

**Comment by Kovah** [comment]
This is currently blocked by issue #148, there will be some changes for language strings. I will keep you updated about this.

**Comment by FanyangMengDev** [comment]
OK, thanks a lot. : )

**Comment by Kovah** [comment]
@MFYDev I optimized some chinese translations. Could you check if they are correct? Thank you!
https://crowdin.com/translate/linkace/79/enus-zhcn?filter=basic&value=3

**Comment by MFYDev** [comment]
Done. The tranlation that you need me to check has been replied and one of them has been corrected.

Thank you for your hard working!

**Comment by Kovah** [comment]
Perfect, many thanks!
Next version with the translations will be released soon.
