### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by FanyangMengDev** [Kovah/LinkAce#142]
When I tried to clear the trash or delete some url permanently in LinkAce, it returns this

Oops! An Error Occurred
The server returned a "405 Method Not Allowed".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Would you please have some check?

**Comment by FanyangMengDev** [comment]
When I tried to clear the "Deleted_at" in the Database, MySQL cannot clear it too, it displays

Incorrect datetime value: '' for column 'deleted_at' at row 1

**Comment by Kovah** [comment]
Ooops. Seems there is something broken. Will be fixed in the next version.

For the deleted_at column: make sure you set a NULL value, instead of an empty string (`""`).

**Comment by FanyangMengDev** [comment]
Thank you so much for your fast reply and answer.

Looking forward to the next version. : )

**Comment by FanyangMengDev** [comment]
By the way, I set deleted_at as "NULL", MySQL still displayed error....

Really drives me crazy that the deleted links cannot be restore or clear permanently.

**Comment by Kovah** [comment]
I will release the new version as soon as possible.
