### ISSUE TITLE
Support for SSO / LDAP

### ISSUE THREAD

**Issue by Kovah** [Kovah/LinkAce#174]
Highly relates to #165
Probably feature for v2.0.

**Comment by Kovah** [comment]
Related issue: #194 Support for OpenID authentication

**Comment by amadeusp** [comment]
Not important for me. I hear people like a lot if they can authenticate with Google, Facebook etc.

**Comment by Kovah** [comment]
LinkAce will not get support for LDAP / SSO yet. The project is searching for a company sponsoring this feature.

More details: https://github.com/Kovah/LinkAce/discussions/671

**Comment by Kovah** [comment]
SSO support is now available in the Beta 3 of LinkAce v2.

### Please test this with your setups, as I have no capacity to do in-depth testing with 10+ services.
