### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by raman325** [Kovah/LinkAce#180]
**Describe the bug**
I was reading through https://www.linkace.org/docs/v1/configuration/user-settings/ and in the Dark Mode section, I saw the following:

Option | Description
-- | --
Permanently Enabled | The dark theme will always be **disabled**.

I **think** `disabled` should be `displayed` to match the description of `Disabled`? (I couldn't find static files for the docs in the repo otherwise I would have submitted a PR)

Looking forward to trying this tool out!

**Comment by Kovah** [comment]
It's corrected. By the way: you can edit the docs in its own repository. https://github.com/Kovah/LinkAce-Website

**Comment by raman325** [comment]
ah good to know, thanks
