### ISSUE TITLE
Add to awesome-selfhosted listing

### ISSUE THREAD

**Issue by MasterGroosha** [Kovah/LinkAce#183]
**Is your feature request related to a problem? Please describe.**
Since this app is not labeled as "stable" (at least, it has version 1.x), I suggest adding your repo to [awesome-selfhosted](https://github.com/awesome-selfhosted/awesome-selfhosted#bookmarks-and-link-sharing) repo, section "Bookmarks and Link Sharing"

**Describe the solution you'd like**
Simply make a PR with a description, link to repo and used technologies (e.g. PHP)

**Additional context**
Initially I was about to do this myself, however I think the developer will find better words to describe his application rather than "Bookmark archive with REST API support"

**Comment by Kovah** [comment]
Thanks for the reminder, will add LinkAce in the next days. :)

**Comment by Kovah** [comment]
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2347

**Comment by Kovah** [comment]
Was merged.
