### ISSUE TITLE
No application encryption key has been specified

### ISSUE THREAD

**Issue by Marco1097** [Kovah/LinkAce#185]
Unfortunately I can't use docker-compose so I had to create the db by hand and modify the .env file with the various values, but the container starts so I think there is some other problem

![immagine](https://user-images.githubusercontent.com/23193188/102639073-cac88b00-4158-11eb-92fd-4cf565568835.png)
![immagine](https://user-images.githubusercontent.com/23193188/102639090-d025d580-4158-11eb-9bd3-0ffd312fcb0f.png)
![immagine](https://user-images.githubusercontent.com/23193188/102639116-d9af3d80-4158-11eb-891c-9404f322e5ce.png)

**Comment by hpapagaj** [comment]
From the docs:

<img width="854" alt="Screenshot 2020-12-18 at 19 16 45" src="https://user-images.githubusercontent.com/72989831/102647163-99a28780-4165-11eb-958f-64b75729d642.png">

**Comment by Marco1097** [comment]
Thanks, i totally missed it
