### ISSUE TITLE
Input type URL is not checked at Quick Add Link

### ISSUE THREAD

**Issue by hpapagaj** [Kovah/LinkAce#187]
**Describe the bug**

Quick Add Link input is missing `type="url"` on the front page:

<img width="1150" alt="Screenshot 2020-12-19 at 01 03 37" src="https://user-images.githubusercontent.com/72989831/102674369-0c2b5b80-4196-11eb-99d0-ff801a78efc0.png">

Which results you can add a link without http(s):// 

<img width="766" alt="Screenshot 2020-12-19 at 01 04 02" src="https://user-images.githubusercontent.com/72989831/102674398-28c79380-4196-11eb-8ce9-a160e73e9700.png">

...and when you click on the link you get a 404 page:

`/links/dsl.sk`

<img width="546" alt="Screenshot 2020-12-19 at 01 05 07" src="https://user-images.githubusercontent.com/72989831/102674420-4563cb80-4196-11eb-8409-ee4d8fdd3d58.png">

On extended add link page (`/links/create`) you added `type="url"` which prevents to enter bad url:

<img width="605" alt="Screenshot 2020-12-19 at 01 06 14" src="https://user-images.githubusercontent.com/72989831/102674522-9d023700-4196-11eb-9a52-cea8232adc5f.png">

---

My suggestion is to add type="url" or even better accept URL in a shortened way (without http prefix), just handle redirects better.

**Comment by Kovah** [comment]
Thank you very much for the report. Clearly missed that one.
