### ISSUE TITLE
Tags on the front page

### ISSUE THREAD

**Issue by hpapagaj** [Kovah/LinkAce#188]
**Is your feature request related to a problem? Please describe.**

In the future can we get a box with existing tags on the front page? Maybe something with like a tag cloud?

![deli-tagcloud](https://user-images.githubusercontent.com/72989831/102675174-af7d7000-4198-11eb-9ca3-f1e92aa137ae.png)

My other suggestion would be to add more links to the front page && focus on searching && quick add links & tags. Quick adding links from home page is working, which is nice, but to add some tags we need to click on edit, then add tags and save. Not very fast process. I think it would be nice to add tags right from the front page with quick link together or in the worst case on the second page. Just some inspiration from del.icio.us (I think this was the best bookmarking site ever):

![How-to-Create-an-Account-and-Submit-Content-to-Delicious-3](https://user-images.githubusercontent.com/72989831/102675634-734b0f00-419a-11eb-8eef-a2c6abaea3f6.png)
![unnamed-3](https://user-images.githubusercontent.com/72989831/102675636-75ad6900-419a-11eb-8351-131256dcfd8b.jpg)
![automate-adding-bookmarks-to-delicio us-1](https://user-images.githubusercontent.com/72989831/102675639-78a85980-419a-11eb-81c2-dfda658e198c.png)

Searching links: when I open LinkAce I want one thing: find my saved link ASAP. For this the suggested tag box would be an option, so we can filter down the results, but also a live search would be excellent (http://meilisearch.com maybe?) right from the front page.

**Comment by Kovah** [comment]
I will keep this open for a future release, because I am currently not sure how to extend the dashboard and what makes the most sense.

If you want to add tags to a link on creation, you should use the regular link adding form, which is only one click away when you are on the dashboard. Same goes for the seach.
