### ISSUE TITLE
Docker environment variables

### ISSUE THREAD

**Issue by Marco1097** [Kovah/LinkAce#189]
**Is your feature request related to a problem? Please describe.**
Using a .env file it's uncomfortable

**Describe the solution you'd like**
Be able to use Docker Environment variables

**Additional context**
Most of the Docker container use environment variables for configuration rather than a config file

**Comment by Kovah** [comment]
I think this is already possible. From the Docs of Laravel, the underlying framework:

> Any variable in your .env file can be overridden by external environment variables such as server-level or system-level environment variables.

Could you test this by moving the variables into the Docker config?

**Comment by Marco1097** [comment]
I try to move this variable into the Docker run command and it seems all to work as expected, it also didn't need more the `./.env:/app/.env`
```
APP_KEY
SETUP_COMPLETED 
DB_CONNECTION
DB_HOST
DB_PORT
DB_DATABASE
DB_USERNAME
DB_PASSWORD
REDIS_PASSWORD
```

Note: 
`SETUP_COMPLETE` was inserted because i had already created the user
`APP_KEY` must be genereted

**Comment by Kovah** [comment]
Thank you for checking this! 👍

I will add this to the docs once I figured out a simple way to add the app key and the setup complete flag.

**Comment by Kovah** [comment]
I added details about the setup and possible pitfalls to the wiki.
