### ISSUE TITLE
Installation instructions for docker noobs?

### ISSUE THREAD

**Issue by f1s3c** [Kovah/LinkAce#191]
I'm a complete docker noob and I literally don't have an idea how to start using this. Since LinkAce doesn't support arm64, I'll have to resort to docker desktop on windows, which makes me even more clueless.

Can anyone help me install, like a literal foolproof guide? I'm good at following instructions, but the guide from the wiki has too many holes to fall through for an inexperienced docker user.

**Comment by Kovah** [comment]
If possible, you may try to install LinkAce without Docker instead, which should be possible on any platform with PHP and MySQL support.

**Comment by f1s3c** [comment]
Well I figured a better option would be to install on my windows pc using docker, since I'm only going to be using my bookmarks when the PC is actually booted, don't want to over-stress my small RPi server since I already have a bunch of stuff on it.

This is what kind of help I'm looking for, installation on Windows Docker desktop.

I don't understand if I'm just supposed to pull the docker image and run it?
If not, am I supposed to also download the source files and edit some files in there?

The run configuration on docker desktop also makes no sense, am I supposed to set up the port or is it going to setup itself (9000)?

Next, the commands on the wiki, am I supposed to run them from CMD or somehow inside docker?

As I said I'm just trying to run the software, not fully learn docker.
It would be pretty useful / future users would be really grateful if you could just post a simple guide to installing, or perhaps have a next->next->complete installation of LinkAce.

Thanks once again.

**Comment by f1s3c** [comment]
I've managed to complete the non docker installation on my raspberrypi.
