### ISSUE TITLE
Add support for third-party S3 servers

### ISSUE THREAD

**Issue by AlexGustafsson** [Kovah/LinkAce#198]
**Is your feature request related to a problem? Please describe.**
The current S3 backup solution uses the Amazon-hosted S3 solution. However, there are a lot of other alternatives, such as a self-hosted minio instance.

**Describe the solution you'd like**
I'd like the ability to specify to use, for example, a minio instance instead of, say, eu-west.

**Describe alternatives you've considered**
None.

**Additional context**
Minio etc. are fully compliant S3 servers, meaning that theoretically this should be easy to support.

**Comment by Kovah** [comment]
Should be easy to extend support for other S3-compatible software.

Could you take a look into this article and test the Minio configuration in the "Setup Minio" section? https://dev.to/crynobone/using-minio-on-laravel-vapor-locally-3kp3

**Comment by AlexGustafsson** [comment]
I'll check it out as soon as possible. Thanks!

**Comment by Kovah** [comment]
Hi, could you check the settings used in the article?
