### ISSUE TITLE
A linkace CLI for the API

### ISSUE THREAD

**Issue by TheJokersThief** [Kovah/LinkAce#200]
Hey! Really love the project and set it up but I was missing a CLI integration for myself and so I built one. Would love to know what you think about :) Thanks for the project 💖

https://github.com/TheJokersThief/linkace-cli

**Comment by Kovah** [comment]
This is awesome, great work!!! 😍
Will add this to the website, have to introduce a third-party tools section or something like that. This is definitely going to help someone.

**Comment by Kovah** [comment]
Added to the website.
https://www.linkace.org/docs/v1/general/third-party-tools/
