### ISSUE TITLE
function getMetaTags get html charset may be false

### ISSUE THREAD

**Issue by igo9go** [Kovah/LinkAce#210]
if html content like this

```
<meta charset='utf-8'>
```

the function `\App\Helper\HtmlMeta::getMetaTags`  get charset wil be false

url link example: https://gitee.com

**Comment by Kovah** [comment]
Could you describe the problem a bit more? What issues is this causing?

**Comment by igo9go** [comment]
just add link `https://gitee.com`, you will look error

**Comment by Kovah** [comment]
I added the URL in the demo and the link was saved successfully with Asian symbols in the title.

If you get an error please share it, otherwise I can't help.

**Comment by Kovah** [comment]
Any news on this?
