### ISSUE TITLE
Dependency cleanup

### ISSUE THREAD

**Issue by Ailothaen** [Kovah/LinkAce#215]
Hello,

I saw that the way the project was distributed (for non-Docker installations) improved since the beginning: now the JS code is already compiled upon release, and PHP dependencies are also downloaded. Thanks for that!

However, when I opened the zip for the release v1.1.0, I noticed the final package is really heavy (68 MB), 66 MB being actually dependencies:

![20210117-191728-001778](https://user-images.githubusercontent.com/11133116/104852173-8f58e200-58f9-11eb-9c15-9bf8888f7112.png)

I guess that some libraries are essential components (laravel for example), but I think some of them could easily get simplified, or even removed (`fakerphp` for example, which is about generating fake data, or `aws` : I think this is related to AWS backup, but almost 20 MB of libraries to perform this task sound a lot)

Do you think this is something that could be easily done? (Maybe with a script that would remove all the useless files in the packaged release?)  
It should not be a priority at all, but this would improve the app "tidiness" and reduce its size greatly, which can be great for those who have small disk space (like on a VPS)

Thanks in advance!

**Comment by Kovah** [comment]
Hi!
Thanks for the heads up on this. I will clean up the dependencies for the next release. Development libraries like Faker will be removed. Not sure about AWS, maybe there is a smaller library that can be used instead of the large SDK.

**Comment by Kovah** [comment]
ZIP file for the latest release is down to 9.33MB from 18MB.
I did not find any replacement for the AWS SDK, so it's not likely to be removed.

**Comment by Kovah** [comment]
I would close this issue now. If you have another idea how to make the package slimmer, feel free to share your ideas.
