### ISSUE TITLE
Shortcut timeout

### ISSUE THREAD

**Issue by hpapagaj** [Kovah/LinkAce#219]
**Describe the bug**
In Shortcuts on iOS when I add a new shortcut, it's timeouting, but the link is still added to LinkAce.

**To Reproduce**
1. Enable Shortcut for Linkace
2. Add link with Linkace's shortcut
3. See error

**Screenshots**
https://www.youtube.com/watch?v=EVydBfAvBiA&feature=youtu.be

**LinkAce setup (please complete the following information):**
 - Version: [e.g. 0.0.43]
 - Installed via: Docker
 - OS: Ubuntu

**Desktop (please complete the following information if applicable):**
 - OS: [e.g. iOS] iOS
 - Browser [e.g. chrome, safari] Shortcuts

**Smartphone (please complete the following information if applicable):**
 - Device: [e.g. iPhone6] iPhone 12
 - OS: [e.g. iOS8.1] IOS 14

**Additional context**

**Comment by Kovah** [comment]
Which LinkAce version do you use? Timeouts should not happen in the latest version.

**Comment by hpapagaj** [comment]
I just upgraded to latest. Finally I no longer get timeout, but still takes about 20 seconds to get confirmation Link saved with ID xy. On the web interface of LinkAce I see instantly as I press on Shortcut.

One more thing would be awesome: add tags while saving with Shortcut. It is somehow possible to ask for tags and save with link?
