### ISSUE TITLE
Version information in footer

### ISSUE THREAD

**Issue by adrianmihalko** [Kovah/LinkAce#220]
It would be a nice feature to show version information in the footer, maybe with information about update available, like PiHole:

<img width="535" alt="Screenshot 2021-01-20 at 12 34 11" src="https://user-images.githubusercontent.com/733361/105169580-02da3980-5b1c-11eb-98ba-a19367c18ca7.png">

**Comment by Kovah** [comment]
Hi!
Version and update information are available in the system settings already. I would leave them in the settings for now.

**Comment by jimmybrancaccio** [comment]
I agree, it would be nice to see this in the footer. Apparently you like to click things @Kovah. However for those of us who don't this would be a great quality of life improvement, and I doubt it would take much effort to add this information into the footer. Another easy win for you... 🤷🏼
