### ISSUE TITLE
Add tags through Shortcut app

### ISSUE THREAD

**Issue by adrianmihalko** [Kovah/LinkAce#221]
It would be a killer feature to add tags ass well when you add link trought the Shortcut app. It simple should ask in a popup for tags you wish to add with the link and send to LinkAce.

**Comment by Kovah** [comment]
I updated the existing Shortcut and created an extended one.

Shortcut asking for title only
https://www.icloud.com/shortcuts/b8741345ad794d158bbf1b91a4d515bf

Shortcut asking for title, description, lists and tags
https://www.icloud.com/shortcuts/d0c6b9bbb74a4f75aa8b7a3c0ff4278c

Could you test both before I publish them?

**Comment by adrianmihalko** [comment]
Wow, very cool. It works fine for new links, but I found a little bug in every Shortcut version. When I add a link and remove later, it doesn't show up in Linkace anymore (neither in export), but if I try to add same link again with Shortcut I get error:

![IMG_0126](https://user-images.githubusercontent.com/733361/105579616-cf034c00-5d87-11eb-94a4-0dcf975cde6a.jpeg)

**Comment by Kovah** [comment]
Glad both work.
Yeah because it's still present in the trash. Try clearing it, that should work.

**Comment by adrianmihalko** [comment]
You are right, now it works like it should. 🤘
