### ISSUE TITLE
Can't save "https://penpot.app/" and don't know why

### ISSUE THREAD

**Issue by jk** [Kovah/LinkAce#230]
**Describe the bug**
I wanted to save `https://penpot.app/` which results in an 500 - Server Error, where's `https://blabla.app/` just works - first I thought it has something to do with the app TLD.

**To Reproduce**
Try to save `https://penpot.app/`

**Expected behavior**
Save the `https://penpot.app/` link

**LinkAce setup (please complete the following information):**
 - Version: v1.2.0
 - Installed via: Docker
 - OS: Ubuntu

**Desktop (please complete the following information if applicable):**
 - OS: macOS 
 - Browser Firefox
 - Version 85.0

**Additional context**
System log has the following error in it:
```
 iconv(): Wrong encoding, conversion from &quot;utf8&quot; to &quot;UTF-8&quot; is not allowed {"userId":1,"exception":"[object] (ErrorException(code: 0): iconv(): Wrong encoding, conversion from &quot;utf8&quot; to &quot;UTF-8&quot; is not allowed at /app/app/Helper/HtmlMeta.php:129) 
```

**Comment by jk** [comment]
It this probably related to https://github.com/Kovah/LinkAce/issues/225? Might have missed that, because the docker images for 1.2.1 wasn't released yet. Anyway, if so, the issue should be closed.

**Comment by Kovah** [comment]
Oh yes, I just saw that the Docker image builds failed. I will correct the build.
The issue should be fixed.
