### ISSUE TITLE
Can't rename a list to change an accent

### ISSUE THREAD

**Issue by secnum** [Kovah/LinkAce#235]
**Describe the bug**
I can't rename a list just to change an accent. The error message "The name has already been taken" appears. For exemple in french : entraînement -> entrainement is not possible (considered as the same word).

**To Reproduce**
1. Go to 'All lists'
2. Click on 'Edit'
3. Change the List Name
4. Click on 'Update List'
5. See error

**Expected behavior**
The name update should apply.

**LinkAce setup (please complete the following information):**
 - Version: 1.2.2
 - Installed via: PHP
 - OS: Ubuntu

**Additional context**
Tags may also be affected.

**Comment by Kovah** [comment]
Hi. This is not an issue with LinkAce itself, but with the database encoding. Because LinkAce relies on the database to check for unique values, `é` and `e` are the same letters if you have `uft8_general_ci` set as you collation. You can read more about that here: #206

**Comment by secnum** [comment]
I just checked my database. 
DEFAULT_CHARACTER_SET_NAME : utf8mb4
DEFAULT_COLLATION_NAME : utf8mb4_bin

**Comment by Kovah** [comment]
Will take a look into this later.

**Comment by m8** [comment]
Also, if you delete a tag and try to create tag with a same name program produces "The name has already been taken".

**Comment by Kovah** [comment]
@m8 this is correct behavior, because the tag is pushed to the trash. Please clear the trash or restore the tag you deleted.

**Comment by m8** [comment]
Oh okay nice feature

**Comment by Kovah** [comment]
Hey @secnum, could you please double-verify that your actual table has the utf8mb4_bin collation? 

![tags table](https://user-images.githubusercontent.com/1816101/109289015-e40b4900-7825-11eb-8074-cc320739b124.png)

I tested the issue and was able to change a tag from `entraînement` to `entrainement`. However, this was only possible by using `utf8mb4_bin`, it did not work with other collations like `utf8mb4_general_ci`.

**Comment by secnum** [comment]
My database has the right collate, my tables too (I just did it one by one) but the lines inside my tables remain in Collation utf8mb4_unicode_ci. I will try to correct this. I don't understand why the database has this behaviour knowing that I specified the right collate when I created it.

**Comment by Kovah** [comment]
I feel you. Database encoding and collations are plain horrible. Hope you can migrate to the new encoding with your data.
