### ISSUE TITLE
Link Check Cronjob Returns False Positives

### ISSUE THREAD

**Issue by jimmybrancaccio** [Kovah/LinkAce#236]
**Describe the bug**

My LinkAce instance seems to report a fair amount of false positives for non-working URLs. When I manually `curl` the link I get a 200 response which I believe is what [LinkAce is looking for](https://www.linkace.org/docs/v1/application/link-checks/) so I am not sure why it reports them as broken.

**To Reproduce**

1. Add any of the following links (see additional context) to your LinkAce instance.
2. Ensure [the cronjob is setup](https://www.linkace.org/docs/v1/setup/post-setup/) for link checking.
3. Wait for the cron to run and report broken links to your email.

**Expected behavior**

I expect that if the documentation says that if a link reports a 200 response when the cron runs it will be considered "good". That when I manually run `curl` against the URL and it returns a 200 response that LinkAce shouldn't report the link as broken.

**Screenshots**

<img width="640" alt="Screen Shot 2021-02-22 at 12 36 45" src="https://user-images.githubusercontent.com/405585/108753671-a8613e00-750a-11eb-86af-63f92e3dbf56.png">

**LinkAce setup (please complete the following information):**

 - Version: v1.2.2
 - Installed via: Docker (Advanced Setup)
 - OS: Ubuntu 20.04.x

**Desktop (please complete the following information if applicable):**

 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information if applicable):**

 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**

Here's the links that are reporting as broken for me but shouldn't be:

- https://signalvnoise.com/posts/218-paradox-of-the-active-user-aka-i-dont-want-to-rtfm
- https://geshl2.com/?sfw=pass1613677351
- https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers
- https://anidiots.guide (returns a 204 which should be considered successful as per [this document](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204))
- http://www.tigernt.com/cgi-bin/cedict.cgi
- https://www.freeformatter.com/cron-expression-generator-quartz.html

**Comment by Kovah** [comment]
LinkAce will also report sites as broken, if the loading time exceeds the limit. Currently, LinkAce aborts the check after 10 seconds. This might be the reason, why perfectly fine websites are reported as broken.

**Comment by jimmybrancaccio** [comment]
@Kovah Sounds great! One thing that could really improve this is providing the reason why the link failed in the email and on the links page itself. That would leave no room for question on _why_ it's considered failed/broken 😁
