### ISSUE TITLE
Add link 500 - Server Error 

### ISSUE THREAD

**Issue by steffenweb** [Kovah/LinkAce#238]
**Describe the bug**
Add link 500 - Server Error 

**To Reproduce**
1. Setup with Docker: Advanced
2. Add Link 
3. Put in https://www.servershop-bayern.de/
4. 500 - Server Error

**Expected behavior**
See Log

**LinkAce setup (please complete the following information):**
 - Version: v1.2.2
 - Installed via: Docker: Advanced
 - OS: Debian Buster LXC in Proxmox

**Desktop (please complete the following information if applicable):**
 - OS: Windows
 - Browser Firefox 
 - Version 86

**Additional context**
I think german umlaute "ä, ü or ö" is the problem. 

[laravel-2021-02-26.log](https://github.com/Kovah/LinkAce/files/6052850/laravel-2021-02-26.log)

**Comment by Kovah** [comment]
Probably related to encoding issues, will take a look later.

**Comment by steffenweb** [comment]
I did update LinkAce to 1.3.0 but still have 1 website/link where i get the 500 error - https://www.privacy-handbuch.de/handbuch_21.htm 

[laravel-2021-03-06(1).log](https://github.com/Kovah/LinkAce/files/6096298/laravel-2021-03-06.1.log)

**Comment by Kovah** [comment]
![](https://giphy.com/gifs/harry-potter-idk-shrug-720g7C1jz13wI)

**Comment by Kovah** [comment]
I worked on a deciated package to get meta details from URLs and added it to LinkAce today. I tested your provided link and it worked. Will release LinkAce 1.3.1 later today.

**Comment by Kovah** [comment]
1.3.1 is released. Could you please verify that it's working?

**Comment by steffenweb** [comment]
Ok it works, it was possible to import all my Bookmarks. Good Job!
