### ISSUE TITLE
Add link - error 500

### ISSUE THREAD

**Issue by sardaukar** [Kovah/LinkAce#240]
**Describe the bug**
Adding this link throws an error.

**To Reproduce**
1. Go to 'https://www.abebooks.co.uk/servlet/BookDetailsPL?bi=22732366225&searchurl=tn%3Dpavane%26sortby%3D20%26pics%3Don'
2. Click on Add Link bookmarklet
3. Click 'Add Link'

**Expected behavior**
Link is added

**Screenshots**
![image](https://user-images.githubusercontent.com/153407/109404421-e375ce00-795d-11eb-9c4a-d04d442e3ec2.png)

**LinkAce setup (please complete the following information):**
 - Version: [1.2.2]
 - Installed via: [Docker]
 - OS: [Debian]

**Comment by Kovah** [comment]
Please follow #238, it's the same issue only with a different url.
