### ISSUE TITLE
Lost password and email not configured

### ISSUE THREAD

**Issue by AlexKalopsia** [Kovah/LinkAce#241]
Hi, 

I have a bit of an annoying issue. I am running LinkAce in a Docker container. I have created my user, but I also forgot my password. I can't reset it because I didn't configure the SMTP server.

I tried bashing in the MariaDB container, finding my user and just setting the password to MD5(mypassword) or PASSWORD(mypassword), but the new passwords are never accepted. 

Any way around this in a way that I don't lose the bookmarks I already added?

**Comment by AlexKalopsia** [comment]
Nevermind, I ended up configuring the SMTP server instead and using the password reset functionality ^^

**Comment by Kovah** [comment]
You can also reset the user password via the command line, which is accessible inside the Docker container.
See https://www.linkace.org/docs/v1/cli/
