### ISSUE TITLE
Bad formatted tags importation

### ISSUE THREAD

**Issue by secnum** [Kovah/LinkAce#242]
**Describe the bug**
When LinkAce crawls the targeted website and the embedded target keywords are separated only by commas with no spaces, LinkAce only takes them for one tag. It breaks the page.

**To Reproduce**
1. Find a website with keywords without space e.g https://www.hdat2.com
2. Wait the crawling

**Expected behavior**
Separated tags in LinkAce

**Screenshots**
<img width="1054" alt="capture" src="https://user-images.githubusercontent.com/25979720/110135687-18a37580-7dcf-11eb-9fd7-7d6c32689c5b.png">

**LinkAce setup (please complete the following information):**
 - Version: 1.2.2
 - Installed via: php
 - OS: Ubuntu

**Comment by Kovah** [comment]
Thanks for the report! Will take a look into this.
