### ISSUE TITLE
Cannot use cron for regular link checking

### ISSUE THREAD

**Issue by aaro-n** [Kovah/LinkAce#245]
**Describe the bug**
According to the official instructions, using docker compose to build applications can be used normally, but cron cannot be used for link detection. Generate a "Cron token" in the "System Settings", access the link through the browser: https://example.example.info/cron/yGuPOXK2RRi8Q482NXk9dmNGn0mIfyQP, directly prompt 403 error.
Note 1: I installed nginx counter-generation linkace on another vps, installed nginx on the first vps, configured reverse proxy and ssl, deployed linkace on the second vps, and opened specific ports to the first vps.
Note 2: Use the second vps for IP access, and http://36.7.xx.xx:8443/cron/yGuPOXK2RRi8Q482NXk9dmNGn0mIfyQP also prompts 403 forbidden to access
Note 3: There is no cron URL in the “Cron Token” interface generated in the “System Settings”
Note 4: The database uses mariadb 5.5

**To Reproduce**
1. Go to 'Generate cron access key'
2. Click on 'Browser visit the link'

**Expected behavior**
Access to cron link prompts 403 error

**Screenshots**

<img width="1116" alt="截屏2021-03-07 下午2 45 32" src="https://user-images.githubusercontent.com/45537680/110231640-fb4be400-7f53-11eb-9756-23320ad99b89.png">

Only generate cron access key, no cron url

<img width="223" alt="截屏2021-02-04 上午7 28 12" src="https://user-images.githubusercontent.com/45537680/110231692-351cea80-7f54-11eb-976e-f82aec804dee.png">

Visit http(s)://domain name or ip/gVcANG31DCJHOtEGYStgzODGGihrOxsC, display 403

<img width="1289" alt="截屏2021-03-07 下午2 51 24" src="https://user-images.githubusercontent.com/45537680/110231790-ecb1fc80-7f54-11eb-99d6-631f37da27d2.png">

Log displayed

**LinkAce setup (please complete the following information):**
 - Version: [1.3.0，1.2.0]
 - Installed via: [ Docker]
 - OS: [ubuntu 20.04]
 - database:[mariadb 5.5]

**Desktop (please complete the following information if applicable):**

**Smartphone (please complete the following information if applicable):**

**Additional context**
<img width="452" alt="截屏2021-03-07 下午2 56 46" src="https://user-images.githubusercontent.com/45537680/110231895-6d70f880-7f55-11eb-86c9-e854b08d123c.png">

APP_URL has been set

**Comment by Kovah** [comment]
I forgot to remove the cron token from the cache. A hotfix is to run the `php artisan cache:clear` command.

**Comment by aaro-n** [comment]
After running the cleanup code "docker exec -it linkace_app_1 php artisan cache: clear", corn has run successfully, you can close this issue
