### ISSUE TITLE
Clarification of Backup Strategy

### ISSUE THREAD

**Issue by jimmybrancaccio** [Kovah/LinkAce#248]
**Describe the bug**

This may or may not be a bug. Looking at `config/backup.php` I see there appears to be a default backup strategy at the bottom of file, however this configuration does not seem to be obeyed as I currently have 23 backups.

**To Reproduce**

1. Setup LinkAce, I am currently using the "advanced" Docker deployment.
2. Configure backups w/ S3.
3. Let the backup process take place, and see it continue to occur.
4. Does it ever remove older backups?

**Expected behavior**

At this point I am not sure what to expect since nothing appears to be documented, except for looking at the `backup.php` file.

**Screenshots**

N/A

**LinkAce setup (please complete the following information):**

 - Version: v1.2.2 (though I see there is a new version - not sure if anything in regards to backups was touched in that version)
 - Installed via: Docker
 - OS: Ubuntu 20.04.x

**Desktop (please complete the following information if applicable):**

N/A

**Smartphone (please complete the following information if applicable):**

N/A

**Additional context**

N/A

**Comment by Kovah** [comment]
You can find more details about application backups in the Laravel-Backup Package by spatie, which provides the feature: https://spatie.be/docs/laravel-backup/v6/introduction

**Comment by jimmybrancaccio** [comment]
Ok, so it's just a matter of running `php artisan` to clean things up.

**Comment by Kovah** [comment]
If you have set up the cron as explained in the documentation, this command should already be run every night. Could you check that?

**Comment by jimmybrancaccio** [comment]
@Kovah Yes, the cron is already configured.

**Comment by Kovah** [comment]
As LinkAce ships with the default configuration of the package, daily backups of the last 7 days are kept. Are older ones deleted or do you have one on storage?

**Comment by jimmybrancaccio** [comment]
@Kovah It appears no backups are deleted. S3 bucket listing:

<img width="813" alt="Screen Shot 2021-03-16 at 17 58 31" src="https://user-images.githubusercontent.com/405585/111390748-42875280-8681-11eb-920f-a88466ad5c5c.png">

I get 2 emails daily, subjects and contents:

**backup::notifications.cleanup_successful_subject**

<img width="679" alt="Screen Shot 2021-03-16 at 17 59 41" src="https://user-images.githubusercontent.com/405585/111390846-6fd40080-8681-11eb-8e89-97dfa15954eb.png">

**backup::notifications.backup_successful_subject**

<img width="679" alt="Screen Shot 2021-03-16 at 18 00 20" src="https://user-images.githubusercontent.com/405585/111390872-7bbfc280-8681-11eb-9488-29e6c2d2a1bc.png">

**Comment by Kovah** [comment]
Okay thanks. Will take a look.

**Comment by Kovah** [comment]
@jimmybrancaccio BTW Did running the clean command manually help?

**Comment by Kovah** [comment]
That's super weird. Have to investigate this.

**Comment by Kovah** [comment]
I have set up backups on my personal LinkAce, but currently not even the backups are created despite having the backups enabled. no idea what's wrong with that.

**Comment by jimmybrancaccio** [comment]
Oddly enough mine seem to be rotating now and it seems to keep 27 backups. 🤷🏼

**Comment by Kovah** [comment]
I found that I had broken my cron job, backups are running now.
Did you upgrade in the last days?

**Comment by jimmybrancaccio** [comment]
I believe I did an upgrade last week. I am on 1.5.0 and the UI notes there's no other upgrades.

**Comment by Kovah** [comment]
Maybe it was a bug in the used package and it was resolved with version 1.5. Well... At least it's working. 🥳 
Will monitor this on my personal setup.

**Comment by jimmybrancaccio** [comment]
Yeah definitely possible. That said, this should probably be documented.
