### ISSUE TITLE
Login not working when behind reverse proxy using https 

### ISSUE THREAD

**Issue by nvoelzow** [Kovah/LinkAce#249]
**Describe the bug**
I am running linkace in a docker container and use a reverse proxy (apache) in front of it to connect from the outside world using https (let's say https://linkace.myproxy) while internally only http is used between linkace and the proxy.

Unfortunately the login does not work, starting with the browser telling me that the form is insecure as it is sending the form data to http://linkace.myproxy (not a relative link that would automatically point to the correct https?) and the login fails without any notification or error message - the browser just loads the same empty login page again.

The login failure could be caused by the generated token to be invalid / CSRF due to different host/protocol?

A system setting for the base-URL to use in any internal links might be useful to fix this and other possible similar issues

Accessing the same container through the local IP of the docker container and using http instead of https works just fine, so overall installation is working including login/credentials/etc.

**LinkAce setup (please complete the following information):**
 - Version: v1.3.1
 - Installed via: Docker

**Desktop (please complete the following information if applicable):**
 - OS: macOS
 - Browser: Chrome and Safari

**Comment by Kovah** [comment]
Hi!
The proxy must pass the following two headers to LinkAce for it being able to correctly determine the URL and http scheme.
```
X-Forwarded-For [hostname];
X-Forwarded-Proto [scheme];
```
Nginx, for example, can be configured like this:
```
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header X-Forwarded-Proto $scheme; 
```
Could you please check this?

**Comment by nvoelzow** [comment]
Indeed, that fixed it - thank you!

I did not have to set the X-Forwarded-For header though

For Apache this works pretty well as proxy config:

```
        ProxyPreserveHost on
        ProxyPass / http://172.10.0.1/
        ProxyPassReverse / http://172.10.0.1/
        RequestHeader set X-Forwarded-Port "443"
        RequestHeader set X-Forwarded-Proto "https"
```

**Comment by Kovah** [comment]
Perfect!
Thank you for sharing the configuration. Will add it to the docs. 😊
