### ISSUE TITLE
Update to 1.4.0 with docker-compose.production.yml configuration file ends in 500 - Server Error 

### ISSUE THREAD

**Issue by steffenweb** [Kovah/LinkAce#252]
Hello, i use the service containrrr/watchtower to automatic update my docker apps. ( https://containrrr.dev/watchtower/ )

Today it runs an update and i get after the login i get the 500 server error. 

I'm not sure if the problem is this recent change:

https://github.com/Kovah/LinkAce/commit/b0058663975f1916e43a643ecdcbf006f9fdf163#diff-939173f100b9faaec94fb740138ad0f6376d79e4317974d4dc28a5b489bab7b8

**LinkAce setup (please complete the following information):**
 - Version: 1.3.1 update to 1.4
 - Installed via: Docker
 - OS: Debian

**Desktop (please complete the following information if applicable):**
 - OS: Windows
 - Browser Firefox
 - Version 87

**Additional context**
watchtower update log. 
[watchtower log.txt](https://github.com/Kovah/LinkAce/files/6213411/watchtower.log.txt)

**Comment by Kovah** [comment]
Hi,
did you follow the upgrade guide for version 1.4?
https://www.linkace.org/docs/v1/upgrade/#version-specific-upgrades

**Comment by steffenweb** [comment]
Ok i made the changes but seems like nothing work. I will roll back a backup.

**Comment by Kovah** [comment]
Could you share any logs? They are located in the container under storage/logs/. Would be helpful for finding the issue.

**Comment by steffenweb** [comment]
There be only old logfiles. 
-rw-r--r-- 1 daemon daemon 87935 Mar 16 18:25 import.2021-03-16.log
-rw-r--r-- 1 daemon daemon 96514 Mar 16 18:35 laravel-2021-03-16.log

The app container "linkace_app_1" don't give any reports when i start it. Nothing to see in Portainer.

These are my configuration files. I censored, APP_URL and passwords.

[docker-compose.yml.txt](https://github.com/Kovah/LinkAce/files/6214158/docker-compose.yml.txt)
[.env.txt](https://github.com/Kovah/LinkAce/files/6214166/default.env.txt)

**Comment by Kovah** [comment]
Does the nginx container output something? I can't see any issues within your files.

**Comment by steffenweb** [comment]
nginx 20:37:12.28 
nginx 20:37:12.28 Welcome to the Bitnami nginx container
nginx 20:37:12.28 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
nginx 20:37:12.28 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
nginx 20:37:12.29 
nginx 20:37:12.29 INFO  ==> ** Starting NGINX setup **
nginx 20:37:12.31 INFO  ==> Validating settings in NGINX_* env vars
nginx 20:37:12.33 INFO  ==> Initializing NGINX
nginx 20:37:12.34 INFO  ==> ** NGINX setup finished! **
nginx 20:37:12.38 INFO  ==> ** Starting NGINX **

**Comment by Kovah** [comment]
Did the website when opening LinkAce give you a generic 500 error? I think nginx should at least log the 500 error, even without a error message or details 🤔

**Comment by steffenweb** [comment]
No error, no log in portainer. I did change back the ports. 

nginx:
    image: bitnami/nginx:1.19
    restart: unless-stopped
    ports:
      - "0.0.0.0:11180:8080"
      #- "0.0.0.0:443:8443"

and get a 404 error now. Seems like the configuration file is still necessary? ( https://github.com/bitnami/bitnami-docker-nginx )

2021/03/26 21:04:57 [error] 29#29: *2 open() "/opt/bitnami/nginx/html/login" failed (2: No such file or directory), client: 172.21.0.1, server: , request: "GET /login HTTP/1.1", host: "xxxxxxxxx
172.21.0.1 - - [26/Mar/2021:21:04:57 +0000] "GET /login HTTP/1.1" 404 117 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0"

**Comment by Kovah** [comment]
Yes... of course. 🤦  I totally messed up the docker-compose files... Sorry.
I added the missing nginx.conf file and updated the docker-compose file.

**Comment by steffenweb** [comment]
Ok good, now i can acces my LinkAce App but my Password/Username seem not to work anymore. when i execute 
 `docker exec -it linkace_app_1 php artisan reset-password`
it reports that A user with this email address could not be found!
So the database seems not to survive the update.

**Comment by Kovah** [comment]
I hope you have a backup at hand. Maybe Portainer deleted the database volume while recreating the stack?

**Comment by steffenweb** [comment]
Yeah i have a backup. and i see there is a unused volume. i will try to restore my data.

**Comment by Kovah** [comment]
Thank you for your patience. Hope you like LinkAce. :)
