### ISSUE TITLE
Undefined Array Key on Second Link added via Bookmarklet

### ISSUE THREAD

**Issue by jtmorris245** [Kovah/LinkAce#253]
On a fresh installation following the Simple Docker setup instructions, when adding links via the bookmarklet, the second link added will fail with error 500, and message in the logs of either:
`Undefined array key "description" {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined array key \"description\" at /app/vendor/kovah/laravel-html-meta/src/HtmlMetaParser.php:142)`
or 
`Undefined array key "user-login" {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined array key \"user-login\" at /app/vendor/kovah/laravel-html-meta/src/HtmlMetaParser.php:142)`

I have yet to find a pattern that causes one over the other, it appears to be random.
I've re-installed with fresh .env files, and cleared volumes, the same issue occurs.
Adding via the quick add in the web UI appears to work, until the bug is triggered, from which time this method also fails with error 500.
**To Reproduce**
Steps to reproduce the behaviour:

1. Install as per the simple docker setup instructions (Tested on Ubuntu Server 20.04)
2. Go through the web UI setup process.
3. Using the bookmarklet add a single link.
4. Then, using the bookmarklet, attempt to add a second link.

**Expected behaviour**
The bookmarklet to correctly add subsequent links.

**LinkAce setup (please complete the following information):**
 - Version: V1.4 ( Main branch Commit fcfd0de)
 - Installed via: Docker
 - OS: Ubuntu 20.04 LTS Server

**Desktop (please complete the following information if applicable):**
 - OS: Windows 10
 - Browser Edge and Chrome

**Comment by Kovah** [comment]
Thank you for reporting this issue. Will take a look into it today.

**Comment by Kovah** [comment]
Issue is fixed with version 1.4.1.
