### ISSUE TITLE
I want to search for bookmarks that are not tagged or listed

### ISSUE THREAD

**Issue by u6k** [Kovah/LinkAce#257]
**Is your feature request related to a problem? Please describe.**
Often, you want to bookmark a number of open web pages as they are, and then calmly edit tags and lists later.  However, there is no way to search for bookmarks that are not tagged or in any list.

**Describe the solution you'd like**
I want you to be able to specify "No tags" and "No list" as search items.  "No tags" will only search for untagged bookmarks.  "No list" searches only bookmarks that are not in any list.

**Comment by u6k** [comment]
Thank you!

**Comment by Kovah** [comment]
You are welcome! Thanks for using LinkAce.
