### ISSUE TITLE
Add batch / bulk editing

### ISSUE THREAD

**Issue by Kovah** [Kovah/LinkAce#26]
Links should be batch-editable, like adding a category, a tag, delete them, set them private,...

Related:
- #379

**Comment by amadeusp** [comment]
I'd love to be able to do that too!

**Comment by kmander** [comment]
Simple bulk creation of bookmarks would be great.

**Comment by JuanRodenas** [comment]
I'd love to be able to do that too!

**Comment by erm-git** [comment]
Just installed linkace and imported my horribly organized existing bookmarks from Chrome. Absolutely would love to see this feature! Until then, I'm importing in chunks to make it more managable. Otherwise, Linkace seems to be the solution I've been looking for.

**Comment by cjx2022** [comment]
Batch edit/delet is important to me, and it's best to batch select links, batch edit tags and list attributes, or batch delete。

**Comment by asymetricbalance** [comment]
+1

**Comment by jotrocken** [comment]
+1

It's not only bulk delete, but it's also bulk add tags or simply select multiple link entries.

**Comment by leoossa** [comment]
+1,
I would love to see this feature reflected in API

**Comment by Kovah** [comment]
Marking this as completed. Links, lists and tags can now be bulk-edited via the UI and the API.

![linkace localhost_links_link-display=2](https://github.com/user-attachments/assets/8b6bd0aa-3aa1-4a8f-85ce-8798a0449631)

![linkace localhost_bulk-edit](https://github.com/user-attachments/assets/3f6c2e6b-a7cd-40dc-8d2a-ffd93bd70bdb)

**Comment by leoossa** [comment]
@Kovah I know that may sound stupid but when I said about API I meant adding in the very first place. And it sounded obvious to me (maybe it wasn't that obvious at all).
The real life issue is that you cannot easily add bulk bookmarks from Android. I tried many solutions, and hoped for LinkAce to satisfy my needs. I don't even need an app, as I can write it myself (already tested), but if there's no API point to communicate I would need to iterate links one-by-one which is cumbersome and not very efficient. Also it makes communication more heavy if you want to properly await statuses.

Would it be possible to add bulk-adding to the API? I'd really appreciate if you could

**Comment by Kovah** [comment]
Will be available from Beta 4. 👍
