### ISSUE TITLE
Can't migrate artisan after updating the files

### ISSUE THREAD

**Issue by e-edgren** [Kovah/LinkAce#260]
**Describe the bug**
I can't upgrade LinkAce due to "Nothing to migrate".

**To Reproduce**
- Download [the files](https://github.com/Kovah/LinkAce/releases/tag/v1.5.0).
- Upload them to the server (replace everything).
- Run `php artisan migrate` in the root folder where the files for LinkAce are.

In other words, exact the same steps as [on the guide](https://www.linkace.org/docs/v1/upgrade/) for upgrading without Docker.

**Expected behavior**
I expect to be able to upgrade from version 1.4.1 to 1.5.0.

**Screenshots**
![image](https://user-images.githubusercontent.com/53869451/114272145-3048cc00-9a15-11eb-8208-d2b188af1c7b.png)

**LinkAce setup (please complete the following information):**
 - Version: 1.4.1
 - Installed via: PHP
 - OS: Debian

**Comment by Kovah** [comment]
That's totally fine. If it says "nothing to migrate", there were no changes required for the database. You can safely continue using LinkAce.
Will add this detail to the documentation.

**Comment by e-edgren** [comment]
Okey, but I still have version 1.4.1. I do not have version 1.5.0 even if I have replaced all files for LinkAce on the web server.

**Comment by Kovah** [comment]
The version is cached for at least a day to prevent too many checks against Github. You can run `php artisan cache:clear`, but there is no urgend need to do this.

**Comment by e-edgren** [comment]
Alright. That worked perfectly :) Thank you!

**Comment by Kovah** [comment]
👍
