### ISSUE TITLE
YouTube thumbnail don’t show when url contains “_”

### ISSUE THREAD

**Issue by jeop10** [Kovah/LinkAce#263]
**Describe the bug**
When adding a new YouTube link, and the video ID contains the `_` character, the thumbnail display a placeholder

**To Reproduce**
1. Go to add link
2. Add a YouTube link like for example: `https://www.youtube.com/watch?v=kKsHo6r4_rc`
3. Check the thumbnail

**Expected behavior**
When adding a YouTube link the proper thumbnail should be displayed.

**Screenshots**

**Additional context**
Also thumbnails images seems not to be centered, probably because on my last commit forgot to add the `background-position: center`

But this is not related to the image not showing 😅

Edit 2: It also happen with the hypen character. URL for reference: `https://www.youtube.com/watch?v=U--CtfjpiAg`

**Comment by Kovah** [comment]
Thanks for the heads up. Will check and correct this.

**Comment by jeop10** [comment]
Happy to help. Let me know if I can be of assistance by creating another PR or something. 

Best regards.
