### ISSUE TITLE
Linkace Addon for Firefox

### ISSUE THREAD

**Issue by daufinsyd** [Kovah/LinkAce#267]
Hello @Kovah,

I just written a small addon for firefox which add a simple button, which does nothing else than running the javascript to open the bookmarlet.

You can find it here https://gitlab.com/daufinsyd/linkace_firefox
Work the same as the bookmarklet script (the description field is not yet implemented).

Given your licence, I also chose GPL v3. Let me know if you want me to change the icon/name (or if you have other concerns) - you can also pm me.
If you're ok with that, I plan to make it available onto the firefox store.

Have a nice day.

**Comment by Kovah** [comment]
Hi! This is awesome! The link leads to a 404 page, maybe the repository is private?

**Comment by daufinsyd** [comment]
Indeed 😄, it's now public

**Comment by daufinsyd** [comment]
Hi,
I added a link to your repository in the description & summary of the addon (or do you want a link to the website ?).
It's awaiting to be reviewed by mozilla : https://addons.mozilla.org/en-US/developers/addon/linkace-bookmarklet

**Comment by Kovah** [comment]
I can't access the page yet, please drop me a line once it's published.

**Comment by daufinsyd** [comment]
good news, the addon is now available https://addons.mozilla.org/de/firefox/addon/linkace-bookmarklet/
I'll keep it in experimental till I fix the description which don't work the same way as the original Bookmarklet

**Comment by Kovah** [comment]
Awesome! Will add it to the docs in the next days. 👍  
Could you add something like "This extension was developed and is maintained by [your name]." to the description? I would like to be clear that this is not an "official" addon.

**Comment by cinetube** [comment]
> good news, the addon is now available https://addons.mozilla.org/de/firefox/addon/linkace-bookmarklet/ I'll keep it in experimental till I fix the description which don't work the same way as the original Bookmarklet

I tried your firefox addon. Your extension doesn't close the popup window automatically after 5 seconds after successful addition of the bookmark. Please fix this issue.

**Comment by daufinsyd** [comment]
Thanks for reporting it @cinetube, I updated the addon with the fix. The review process by mozilla is pending.
