### ISSUE TITLE
Huge Blank on mobile browser when log in

### ISSUE THREAD

**Issue by MFYDev** [Kovah/LinkAce#268]
**Describe the bug**
There is a huge blank on the LinkAce logo when access it with mobile browser when log in.

**To Reproduce**
1. set only log in user can use it
2. use mobile browser to access linkace
3. See error

**Screenshots**
![Screenshot_2021-04-19-23-56-32-698_com microsoft emmx](https://user-images.githubusercontent.com/53750381/115266952-3d7b5e80-a16b-11eb-9000-6b6656eed78f.jpg)

**LinkAce setup (please complete the following information):**
 - Version: 1.6.1
 - Installed via: php
 - OS: Ubuntu

**Smartphone (please complete the following information if applicable):**
 - Device: Mi 11 Ultra
 - OS: Android 11
 - Browser: Microsoft Edge
 - Version latest

**Comment by Kovah** [comment]
I will release a corrected version in a minute

**Comment by MFYDev** [comment]
Thank you so much Kovah.

Can confirm this issue is solved.

**Comment by Kovah** [comment]
Thank you for the fast report!
