### ISSUE TITLE
Add link - Error 500

### ISSUE THREAD

**Issue by saharandromedary** [Kovah/LinkAce#274]
**Describe the bug**
500 Server Error when adding a Link. Some kind of issue with thumbnail.

**To Reproduce**
1. Go to Add Link page
2. Put url as: https://www.imgix.com/
3. Click add link
4. 500 - Server Error

**Expected behavior**
Link added

**LinkAce setup (please complete the following information):**
 - Version: v1.6.1
 - Installed via: Docker Advanced
 - OS: CentOS 7

**Additional context**
Some kind of issue with the thumbnail being too long for the database
[laravel-2021-05-01.log](https://github.com/Kovah/LinkAce/files/6410418/laravel-2021-05-01.log)

**Comment by Kovah** [comment]
Thank you for the report. Will take a look.
