### ISSUE TITLE
Postgres Support

### ISSUE THREAD

**Issue by luiscachog** [Kovah/LinkAce#275]
**Is your feature request related to a problem? Please describe.**
There is no problem involved here, just wondering if sometime soon you are going to add Postgres as a DB

**Describe the solution you'd like**
Can choose between Postgres and MySQL as a DB

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Kovah** [comment]
You can already use Postgres, it is not supported by the automatic setup yet.
In your `.env` file, properly configure the database credentials and change `DB_CONNECTION=mysql` to `DB_CONNECTION=pgsql`
Instead of starting the setup, run those both commands to prepare the database and create an admin user:
```
php artisan migrate
php artisan registeruser
```
(Prepend `docker exec -it linkace_app_1` if you are using Docker.)

Will keep this open for a possible support in the setup, but it has no priority for me right now.

**Comment by inspector71** [comment]
> 
> 
> You can already use Postgres, it is not supported by the automatic setup yet.
> In your `.env` file, properly configure the database credentials and change `DB_CONNECTION=mysql` to `DB_CONNECTION=pgsql`
> Instead of starting the setup, run those both commands to prepare the database and create an admin user:
> 
> ```
> php artisan migrate
> php artisan registeruser
> ```
> 
> (Prepend `docker exec -it linkace_app_1` if you are using Docker.)
> 
> Will keep this open for a possible support in the setup, but it has no priority for me right now.

Looking at Linkace specifically for PostrgreSQL support. Great that Linkace can work with PostgreSQL now. Is there a firm commitment to keep Linkace compatible with PostrgreSQL though?

**Comment by Kovah** [comment]
> Is there a firm commitment to keep Linkace compatible with PostrgreSQL though?

LinkAce uses Laravel Eloquent as an abstraction layer, which supports MySQL, Postgres, SQL Server and SQLite by default. I doubt that I will use any platform-specific queries in the future.

**Comment by Kovah** [comment]
Glad you like LinkAce! 😊

I will keep this open to document Postgres stuff in the documentation.

**Comment by inspector71** [comment]
> Glad you like LinkAce! 😊

Like yes, conceptually in many respects. 

Have it running myself? Not just yet :)

**Comment by Kovah** [comment]
I added instructions for Postgres to the docs.

**Comment by inspector71** [comment]
> 
> 
> I added instructions for Postgres to the docs.

Thank You! Apologies I took so long to say that. Thought posting a direct link might be helpful. Presumably this is the documentation link here? ...

https://www.linkace.org/docs/v1/setup/setup-with-postgresql/

Brilliant :)

Thank you again for all your hard work. Highly appreciated.
