### ISSUE TITLE
strtotime(): Epoch doesn't fit in a PHP integer

### ISSUE THREAD

**Issue by sinkaszab** [Kovah/LinkAce#286]
While importing bookmarks exported from pinboard.in, import process throws exception: strtotime(): Epoch doesn't fit in a PHP integer

1. https://pinboard.in/settings/backup
2. Click on 'HTML' (https://pinboard.in/export/format:html/)
3. Import downloaded HTML into LinkAce
4. strtotime(): Epoch doesn't fit in a PHP integer

[laravel-2021-06-11.log](https://github.com/Kovah/LinkAce/files/6637442/laravel-2021-06-11.log)

**Expected behavior:**

A. Exception points to record being imported for debugging purposes.
B. Offers to fix record on-the-fly.
C. Imports pinboard.in exports without error.

**LinkAce setup:**

 - Version: 1.6.3
 - Installed via: PHP
 - OS: Raspbian

**Comment by Kovah** [comment]
Hi! Thanks for reporting your issue. Did you take a look at #255?

**Comment by sinkaszab** [comment]
I updated the libseccomp package, but it didn't resolve the issue.

`libseccomp2/buster-backports,now 2.4.4-1~bpo10+1 armhf [installed]`

**Comment by Kovah** [comment]
I think I can't help with this then. I have no device here for testing things like that. I can only suggest that yu search for similar issues, because it's linked not to Linkace itself but running PHP.

An alternative would be to use Docker.

**Comment by sinkaszab** [comment]
For anybody who needs instant fix using a 32 bits operating system:

Open the file below and replace `setExpires` with the code below:

`${PATH_TO_APP}/vendor/guzzlehttp/guzzle/src/Cookie/SetCookie.php`

```php
/**
     * Set the unix timestamp for which the cookie will expire.
     *
     * @param int|string $timestamp Unix timestamp or any English textual datetime description.
     */
    public function setExpires($timestamp): void
    {
        if (\is_numeric($timestamp)) {
            $this->data['Expires'] = (int) $timestamp;
        } else {
            $ts = new \DateTime($timestamp);
            if (($yr = (int) $ts->format('Y')) >= 2038) {
                $years = ($yr - 2038) + 1;
                $this->data['Expires'] = $ts->modify("-${years} years")->getTimestamp();
            } else {
                $this->data['Expires'] = \strtotime($timestamp);
            }
        }
    }
```

I still think the right solution would be to fix the unnecessarily big expiration time.

**Comment by Kovah** [comment]
I thought about this and decided to not fix this. It's caused by devices running 32 bit systems, which are obsolete.
If a user finds an easy way to handle this issue without digging through third-party code, feel free to submit a pull request to my library https://github.com/Kovah/laravel-html-meta, which handles the meta generation for LinkAce.
