### ISSUE TITLE
500 Error adding a link. 

### ISSUE THREAD

**Issue by LilTrublMakr** [Kovah/LinkAce#291]
**Describe the bug**
After a fresh install using Docker and PostgreSQL, you are unable to add links. Logs says that the "thumbnail" column of the links table does not exist. 

**To Reproduce**
1. Fill out info to add new link.
2. Receive 500 error.

**Expected behavior**
New link added without 500 error.

**Screenshots**
Logs: https://pastebin.com/jicEsK3t

**LinkAce setup (please complete the following information):**
 - Version: v1.6.3
 - Installed via: Docker
 - OS: UNRAID

**Additional context**
I am using PostgreSQL and have followed steps 1-4  [here](https://www.linkace.org/docs/v1/setup/setup-with-docker/simple/), and then the 'with Docker' instructions [here](https://www.linkace.org/docs/v1/setup/setup-with-postgresql/). I am able to log in and save settings fine. It seems to be only when I try to add a link when I get an error.

Looking at the logs, it looks like it is trying to save into "thumbnails" in the links table but no such column exists. Below is an image from a fresh installation outline above.

https://i.imgur.com/TvYo9iJ.png

I manually went in and added the column using "ALTER TABLE links ADD COLUMN thumbnail character varying(191) NULL" and ran a test and I am able to add links now.

**Comment by Kovah** [comment]
Thank you for reporting this! I'll see if I can test this with Postgres. Maybe some of the database changes failed.

**Comment by Kovah** [comment]
I have testes this with a clean Postgres database and I am able to add links after the setup. Could you please run `php artisan migrate` and try again?

**Comment by Kovah** [comment]
Please reopen the issue if you need further help.
