### ISSUE TITLE
[Feature Requeast] An api that could get a link by its url

### ISSUE THREAD

**Issue by Creling** [Kovah/LinkAce#293]
**Is your feature request related to a problem? Please describe.**

I am writing an extension for LinkAce. The extension should behaver differently when current page is or is not in LinkAce. However, I cannot find an api which could tell the extension whether current page is in LinkAce or not, except for fetching all links which is costly.

**Describe the solution you'd like**

I think LinkAce should allow users to get a link by its url instead of link-id only, and if the url is not in LinkAce, an error ought to be return.

**Comment by Kovah** [comment]
Hi! I just noticed that I did not document the search endpoint for links.
Could you try `/api/v1/search/links` and pass the URL of the link as a `query` parameter to it? This should work. If you get a result, there is a link already saved.

**Comment by Creling** [comment]
ah, it works, thank you :)

**Comment by Kovah** [comment]
Awesome!
Will keep this open to document the endpoint.

**Comment by Kovah** [comment]
Link search endpoint was added.
