### ISSUE TITLE
Add API query parameters to customize paginations

### ISSUE THREAD

**Issue by Creling** [Kovah/LinkAce#294]
**Is your feature request related to a problem? Please describe.**

It is another api request for the extension. :)

Currently, we do autocomplete depend on the `/api/v1/search/*`. Each time users type in a character will invoke a search requests which brings in notable latency. 

![image](https://user-images.githubusercontent.com/43109504/124143829-05bf5a00-dabe-11eb-8cbb-f76cfffaa938.png)

Since the number of our tags is less than 500 most of the time, it is ok to fetch all tags (< 10KB) into local memory one time and match them with users' inputs. In that situation, we don't need another http request until the user submit the link which will mitigate the latency during autocomplete.

Yes, we could fetch all tags by `/api/v1/tags`, however, we need to access the api recursively due to the pagination, which is not efficient.

**Describe the solution you'd like**

`/api/v1/search/lists` & `/api/v1/search/tags` might be able to accept a `*` to return all tags/links.

**Comment by Kovah** [comment]
That's a great idea. Will plan this for one of the next versions. 👍

**Comment by Kovah** [comment]
Linkace will accept a `per_page` query parameter which can be used to control how many items will be returned. Set it to 0 and all results will be returned. Any other number > 0 will limit the returned items to that amount.

Example: `http://linkace.localhost/api/v1/links?per_page=0`
