### ISSUE TITLE
Announce a new extension for Chrome/Edge.

### ISSUE THREAD

**Issue by Creling** [Kovah/LinkAce#295]
As I said before, I was writing an extension #293  . Now I consider it has meet some basic need so I decide to publish it. :) Currently, it is under chrome web store reviews. 

Anyone who is interested in it could check its [repo](https://github.com/Creling/Yet-Another-LinkAce-Extension) and use it under browser development mode. Issues & Stars & PRs are appreciated.

Since I eat my own dog food and the extension now cannot satisfied my need 100%, the development is still going on.

**Comment by Kovah** [comment]
This looks so good! Please leave a note when the extension was published, I'll add it to the wiki then. 👍

**Comment by Creling** [comment]
> This looks so good! Please leave a note when the extension was published, I'll add it to the wiki then. 👍

I will update this issue as soon as the extension passes the review. :)

**Comment by Creling** [comment]
v0.1.1 is [available](https://chrome.google.com/webstore/detail/yet-another-linkace-exten/ladekkfhihppgfcjgaimgggecekfhmho) now.
v0.1.2 is under reviews.

**Comment by Kovah** [comment]
Added the extension to the list: https://www.linkace.org/docs/v1/general/third-party-tools/
Thank you so much!

**Comment by Creling** [comment]
> Added the extension to the list: https://www.linkace.org/docs/v1/general/third-party-tools/
> Thank you so much!

Glad to hear that, thank you :)
