### ISSUE TITLE
Add Apis that search links by title or description

### ISSUE THREAD

**Issue by Creling** [Kovah/LinkAce#296]
**Is your feature request related to a problem? Please describe.**

Sometime, the url of a link doesn't contain enough information to remind us of the link and we need extra info from page title, page description and so on. It will be helpful if we can search links by title and description. Currently, We can search links by title & description via the web interface, however, there is a lack of relevant Apis.

**Describe the solution you'd like**

Add a `type` para to `/api/v1/search/links` and then  `/api/v1/search/links?query=<query>&type=title` will search a link by title.

**Comment by Kovah** [comment]
Hi!
you can enable searching by title and/or description by passing `search_title=1` or `search_description=1` to the search query. If you need to search _only_ for title and/or descrption, I would have to change that.

**Comment by Creling** [comment]
> enable searching by title and/or description by passing `search_title=1` or `search_description=1`

ahh, that is the api I need! I don't need to merge the search results from title only & description only & url only manually.

**Comment by Kovah** [comment]
I updated the API docs with the search endpoint and updated some other missing definitions.
https://linkace.stoplight.io/docs/api-docs/reference/LinkAce-API.v1.yaml/paths/~1api~1v1~1search~1links/get

**Comment by Kovah** [comment]
Did this work for you? Anything else you need?

**Comment by Kovah** [comment]
Please reopen the issue if you need further help.
