### ISSUE TITLE
Card UI for bookmark items

### ISSUE THREAD

**Issue by cantunborn** [Kovah/LinkAce#305]
**Is your feature request related to a problem? Please describe.**
Currently the UI has large amounts of padding and it is very homogeneous. Images are much easier to differentiate, so there should be an option to show images as the biggest identifier for a bookmark, with less padding so as to utilize space efficiently.

**Describe the solution you'd like**
A Card UI option with the bookmark image at the top with all information about it below it in rows, with least padding as possible. This will allow all one tell all items apart in a listing, while using maximum space with reduced padding.

**Describe alternatives you've considered**
The current maximum details UI has lots of unnecessary padding, even though it shows a lot of information. This results in less number of items in a listing page (for example on a mobile device). It is possible to improve the current max details UI.

**Additional context**
As a starting point, the cards UI in the raindrop android app implements this very well, where images are front and center and showing all information is also toggleable (like hiding description, tags, etc.). Another improvement can be to include the max details UI in the search page, instead of the tabular format. The main reasoning behind this issue is that text is harder to identify than images or favicons.

**Comment by Kovah** [comment]
Marked this as planned as It's quite a good idea. I'll see if I can put together a good solution with large cards with many details.

Could you post some screenshots of the Raindrop ui here as a reference?

**Comment by cantunborn** [comment]
There are some screenshots provided on the google play store page for the raindrop app https://play.google.com/store/apps/details?id=io.raindrop.raindropio.

However, I think it would be best if you operate it yourself using a dummy account with the android app to test it better for the linkace implementation.
