### ISSUE TITLE
Expose params on the bookmarklet url for tags and lists

### ISSUE THREAD

**Issue by agrider** [Kovah/LinkAce#308]
**Is your feature request related to a problem? Please describe.**
I would like the ability to pass the list and tags to be added to into the bookmarklet URL to pre-populate lists within the pop-up window as I do with the url, title, and description.

I use an RSS reader application to get my news/content and then funnel articles/links I don't have time to read or wish to save into Linkace from there. My reader and linkace lists are mirrored such that an article coming into a list of feeds labeled "development" that I save to Linkace lands in a list called "development" in Linkace as well. I've configured my reader app to invoke the bookmarklet when I hit save and that app replaces placeholders for me like the URL and Title of the article to save. This works swimmingly. However, I can't currently pre-populate the lists or tags fields as I'm not able to discern any param names that the bookmarklet will use to prepopulate those fields and that means I have to duplicate clicks that my reader app would populate for me if the bookmarklet exposed an input param for the lists and tags fields like it does with title, url, and description.

**Describe the solution you'd like**
I would like to add the target list(s) as a parameter to the bookmarklet like we have for the url, title, and descriptions. That way we can set upstream apps that have share features to invoke the bookmarklet and pre-populate lists and tags based on data those apps already have available and are capable of sharing with the bookmarklet.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by Kovah** [comment]
Hi, thanks for your feature request.
I am always surprised how people integrate LinkAce into their workflows. I added the idea to the roadmap and I am quite optimistic that it will be included in the near future as it should be not that hard to add this feature. The only obstacle I can think of is that using tags with `&` would be a problem.
I guess you would use the tags as names, and not their IDs?

**Comment by agrider** [comment]
Yeah, I hadn't considered that the tags / lists would be ultimately passed back to the backend as ID rather than name by the modal, but yes ideally the behavior would be to allow the tags and lists to be passed to the bookmarklet modal as text and then have the modal do the lookup in the background, assign the right ID if it exists and create a new tag if one with that text doesn't already exist, the way the free form fields allow you to do manually right now. Basically just treat what is passed to the bookmarklet as if it had been put into the fields after the modal opened.

**Comment by Kovah** [comment]
You can now append tags and lists to the bookmarklet by using the `tags` and `lists` query parameter, with tags and lists as names. They must not contain `&` and must be divided by a comma.
