### ISSUE TITLE
php-pdo missing on Installation when pdo_mysql extension is not installed

### ISSUE THREAD

**Issue by CoLuxe** [Kovah/LinkAce#310]
On Debian 11, php8.0

I wanted to use Postgresql so i have pdo_pgsql/php8.0-pgsql installed.
The Installer shows PDO missing until I install php8.0-mysql which shouldnt be necessary.

Edit: Changing the Database type to pgsql in .env changes nothing.

**Comment by Kovah** [comment]
Hi
I am not offering any support for custom installations and PHP extensions, so I suggest posting your issue to the community forum: https://community.linkace.org/

If changing the database type to pgsql does not work, please try `php artisan config:clear`.

**Comment by Kovah** [comment]
Please re-open this issue if you have any feedback or need further help.
