### ISSUE TITLE
FORCE_HTTPS not working

### ISSUE THREAD

**Issue by krylm** [Kovah/LinkAce#317]
I am not sure about Laravel framework, but I didn't find any mention of force_https configuration in whole codebase. I tried to set .env variable to force HTTPS protocol on links shown in every page from LinkAce, but without any success.

I have running Apache 2.4 with ProxyPass to docker (Docker version 20.10.8) container running LinkAce version 1.6.4. 

Domain directed to Apache has https protocol, proxy is redirected to :80 port with LinkAce container.
Every link inside website is http:// and after submitting any form I am getting warnings from Google Chrome that I am going to unsecure page.

I thought that .env variable **FORCE_HTTPS=true** and restarting container makes change and every link inside app will be forced to HTTPS protocol. I also tried to force http protocol with setting **APP_URL**, but with same result. Without any success.

I am not sure if the problem is on my side with some forgotten configuration or if the codebase is not supporting this configuration variable.

When I add these lines to AppServiceProvider.php it is working correctly:
https://github.com/Kovah/LinkAce/blob/main/app/Providers/AppServiceProvider.php#L21

```
        if ( env('FORCE_HTTPS', false) ) {
                \URL::forceScheme('https');
        }

```

**Comment by Kovah** [comment]
Hi, could you check if you correctly configured your proxy settings like this: https://www.linkace.org/docs/v1/setup/setup-with-docker/advanced-configuration/#running-linkace-behind-a-proxy-load-balancer

**Comment by krylm** [comment]
Thanks a lot. I didn't find that page when trying to solve that issue. I've tried only one of two headers mentioned and it didn't work. With second line mentioning port it works like a charm. Thanks!
