### ISSUE TITLE
Bookmarklet for adding a site - behave as edit

### ISSUE THREAD

**Issue by krylm** [Kovah/LinkAce#318]
As I have 10+k bookmarks, it would be nice to add small change to bookmarklet behaviour if it is possible.
I am not sure if some page is included in bookmarks or not.

Now when I run bookmarklet, fill all tags and submit form, I get error that url is already present in database.

**Describe the solution you'd like**
It would be nice to prefill form, when URL exists in database and show all tags and notes which was stored (edit like mode). And only modify few tags and save changes or only close bookmarklet window (when all is ok).

Thanks for consideration of this change!

**Comment by Kovah** [comment]
Thanks for posting your idea.
It's similar to https://github.com/Kovah/LinkAce/issues/277 where this idea is extended to work everywhere, not just the bookmarklet.
I could imagine that, for the beginning, Linkace could display a link in the creation form like "A bookmark with this url already exists. Do you want to edit it?" with "edit it" being a link to the edit form. That would be easy to implement as the URL is checked at the beginning anyway.

**Comment by krylm** [comment]
Ahh, I tried to search similari issue but did'nt find it.

It would be nice at least know that same url is already stored. Thanks!
