### ISSUE TITLE
Clarify Purpose of 'Splash Screen'

### ISSUE THREAD

**Issue by jimmybrancaccio** [Kovah/LinkAce#325]
When visiting the main page of your LinkAce instance you're presented with what I am calling a 'splash screen'. Is there any reason that this screen is presented instead of the login screen if you're not logged in? It just adds an extra click in the process instead of just being able to log yourself in.

![image](https://user-images.githubusercontent.com/405585/140527369-17c5d332-b105-40c3-9228-81f14682c986.jpeg)

Thanks,

**Comment by Kovah** [comment]
Hi!
LinkAce would show the links for guests here if the guest mode would be disabled. So to speak, the splash screen is basically for consistency. But you are right, if guest mode is disabled, the login screen should be displayed right away.

**Comment by jimmybrancaccio** [comment]
Ah, that totally makes sense for Guest Mode! It would be great though if it went directly to the login page when Guest Mode is not enabled! 😃
