### ISSUE TITLE
Cannot access linkace via domain with ngnix proxy 

### ISSUE THREAD

**Issue by Jayy001** [Kovah/LinkAce#326]
**Description of the Issue**
I cannot access linkace via the domain with reverse proxy I setup. In the `.env` I have the "APP_URL" set to `http://bookmarks.mydomain.me` and on the nginx proxy container environment variables I have `VIRTUAL_HOST` set to `bookmarks.mydomain.me`. 

**Steps to reproduce**
1. Setup https://hub.docker.com/r/jwilder/nginx-proxy
2. Setup https://www.linkace.org/docs/v1/setup/setup-with-docker/advanced/
3. Set "APP_URL" to https://yourdomain.me
4. Re-make `linkace_nginx_1 ` container with env variable `VIRTUAL_HOST` set to `yourdomain.me`

**Expected behavior**
Be able to access link ace via the domain, not just the  ip:port

**LinkAce setup (please complete the following information):**
 - Version: v1.7.0 
 - Installed via: Docker
 - OS: Ubuntu 20

**Comment by Kovah** [comment]
I just noticed that the wiki is not correct. Could you also copy the [nginx.conf](https://github.com/Kovah/LinkAce/blob/main/nginx.conf) file from the files to your setup and restart the nginx container?

**Comment by Jayy001** [comment]
Done, still doesn't work sadly

**Comment by Jayy001** [comment]
I'm getting this error now:

```
2021/11/06 19:19:35 [emerg] 1#1: host not found in upstream "app" in /opt/bitnami/nginx/conf/server_blocks/linkace.conf:48

nginx: [emerg] host not found in upstream "app" in /opt/bitnami/nginx/conf/server_blocks/linkace.conf:48
```

**Comment by Kovah** [comment]
Hm okay, I have to take a deeper look. Will probably take a while, currently have little free time.

**Comment by Jayy001** [comment]
No problem

**Comment by Jayy001** [comment]
Update: Here is the actual error log
```
nginx.1     | 2021/11/06 22:45:51 [error] 203#203: *120 connect() failed (111: Connection refused) while connecting to upstream, client: <ip>, server: links.domain.me, request: "GET / HTTP/2.0", upstream: "http://<ip>:89/", host: "links.domain.me"
```

**Comment by Jayy001** [comment]
With a bit of trying everything, I finally figured out the problem: ports. I made a bit of a mistake as I was using 2 nginx proxies:

Linkace app (82) -> Linkace app nginx proxy -> (8080) -> My proxy -> (80). Instead of using the `8080` port to access the proxy I was using the `82` which wasn't actually open so that's why it was being refused!

**Comment by Kovah** [comment]
Ah! Glad you solved this.
