### ISSUE TITLE
2FA does not work correctly

### ISSUE THREAD

**Issue by hekeki** [Kovah/LinkAce#328]
If i setup 2FA and copy the alternative link and paste it into Enpass App (or andOTP), the code is generated but does not match when i try to login (The Reason why i use the alternative link: I tried to take a picture of the qrcode, but this is not possible with my smartphone)

**To Reproduce**
1. Enable 2FA
2. Copy the alternative link and paste it to an Authenticator App like Enpass or andOTP
3. Save and copy recovery codes
4. Logout and Login
5. Insert 2FA Code -> Fail
6. Login with recovery code works 

**Expected behavior**
2FA Code is valid 

**LinkAce setup:**
 - Version: v1.7.0
 - Installed via: Docker
 - OS: Alpine Linux

**Desktop:**
 - OS: macOS
 - Browser firefox
 - Version 94.0.1

**Comment by Kovah** [comment]
Could you try to setup 2FA with the secret of the URL, e.g. `?secret=ABC456...` without anything else and check if it's working then?

**Comment by hekeki** [comment]
I have tried to use these three

otpauth://totp/LinkAce:USER%40HOST.com?secret=Z4C4NBIKMNVWVWEC&issuer=LinkAce&algorithm=SHA1&digits=6&period=30
secret=Z4C4NBIKMNVWVWEC
Z4C4NBIKMNVWVWEC

All of these works fine, the code is generated, and the codes are always the same

But after logout, i try to login with the generated code, but this wont work.

**Comment by Kovah** [comment]
> No application encryption key has been specified

Huh? 😳
That's really weird. I'll take a closer look when I have the time. Maybe there's something wrong with the way 2FA is handled.

If you want, you could try to generate a new key. But you should disable 2FA before. To generate a new key, run `php artisan key:generate`. I am not 100% sure but it could be possible that you have to reset your password after that.

**Comment by hekeki** [comment]
I have created a new key, reset the password ... same error
I also uninstalled the entire app (even delete /var/lib/docker) and did a reinstall ...  same error

**Comment by Kovah** [comment]
I will keep this open for further investigation, but I wasn't able to reproduce this issue, especially that no encryption key was set.

**Comment by hekeki** [comment]
I have found the error. The server time was not synchronous. The clock was one minute behind.
The ticket can be closed.
