### ISSUE TITLE
Disable Registration

### ISSUE THREAD

**Issue by tefod-zz** [Kovah/LinkAce#330]
Is there way to disable the user registration, so that it can be maintained by some users and the rest are just guests?

**Comment by Kovah** [comment]
Hi. There is no user registration to disable. LinkAce can currently be used by a single user only.

**Comment by tefod-zz** [comment]
Ouhh. Thx. Your right obviously. I tested yesterday so many bookmark solutions (Shiori, NextCloud, xBrowserSync, TeamBookmark and LinkAce) so that i got probably confused.

**Comment by geekedtv** [comment]
> Hi. There is no user registration to disable. LinkAce can currently be used by a single user only.

Any plans to add user registration to use this as a public archive?

**Comment by Kovah** [comment]
Probably not. Even for the next big version there is no public signup planned.
