### ISSUE TITLE
Custom User Agent

### ISSUE THREAD

**Issue by jerptrs** [Kovah/LinkAce#334]
**Is your feature request related to a problem? Please describe.**
Yes, some websites block unknown user-agents. I've had a link which returned HTTP 401 when adding the link, from any other browser the website works fine.

Right now the user agent is unknown, tested with [express-useragent](https://www.npmjs.com/package/express-useragent)

```json
{
  "isYaBrowser": false,
  "isAuthoritative": false,
  "isMobile": false,
  "isMobileNative": false,
  "isTablet": false,
  "isiPad": false,
  "isiPod": false,
  "isiPhone": false,
  "isiPhoneNative": false,
  "isAndroid": false,
  "isAndroidNative": false,
  "isBlackberry": false,
  "isOpera": false,
  "isIE": false,
  "isEdge": false,
  "isIECompatibilityMode": false,
  "isSafari": false,
  "isFirefox": false,
  "isWebkit": false,
  "isChrome": false,
  "isKonqueror": false,
  "isOmniWeb": false,
  "isSeaMonkey": false,
  "isFlock": false,
  "isAmaya": false,
  "isPhantomJS": false,
  "isEpiphany": false,
  "isDesktop": false,
  "isWindows": false,
  "isLinux": false,
  "isLinux64": false,
  "isMac": false,
  "isChromeOS": false,
  "isBada": false,
  "isSamsung": false,
  "isRaspberry": false,
  "isBot": "guzzlehttp",
  "isCurl": false,
  "isAndroidTablet": false,
  "isWinJs": false,
  "isKindleFire": false,
  "isSilk": false,
  "isCaptive": false,
  "isSmartTV": false,
  "isUC": false,
  "isFacebook": false,
  "isAlamoFire": false,
  "isElectron": false,
  "silkAccelerated": false,
  "browser": "GuzzleHttp",
  "version": "7",
  "os": "unknown",
  "platform": "unknown",
  "geoIp": {},
  "source": "GuzzleHttp/7",
  "isWechat": false,
  "electronVersion": ""
}

```

**Describe the solution you'd like**
A settings options to set a custom user-agent. Something like a text input field where someone can set the user-agent string conforming the [HTTP](https://httpwg.org/specs/rfc7231.html#header.user-agent) specification.

**Comment by Kovah** [comment]
I added an issue for the helper I am using. 
https://github.com/Kovah/laravel-html-meta/issues/2

**Comment by Kovah** [comment]
You can now set a custom user agent in your .env file.
See http://localhost:1313/docs/v1/configuration/system-settings/#advanced-system-settings

**Comment by jerptrs** [comment]
Thank you!

**Comment by Kovah** [comment]
Thank you for your donation! ☺️
