### ISSUE TITLE
Unable to import in 1.7.0 (both HTML and CVS) saved bookmarks from 1.4.1

### ISSUE THREAD

**Issue by gianter962** [Kovah/LinkAce#337]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**LinkAce setup (please complete the following information):**
 - Version: [e.g. 0.0.43]
 - Installed via: [e.g. PHP, Docker]
 - OS: [e.g. Ubuntu, CentOS, Windows]

**Desktop (please complete the following information if applicable):**

**Smartphone (please complete the following information if applicable):**

**Additional context**

**Comment by gianter962** [comment]
To Reproduce
Steps to reproduce the behavior:

Go to 'Import, select exported file HTML or CVS, start import.
See error -- Something went wrong while trying to import the bookmarks. Please consult the application logs.
Expected behavior Bookmarks saved

Screenshots
Please look at attached screenshot

LinkAce setup (please complete the following information):

Version: [1.7.0]
Installed via: [Docker]
OS: [Manjaro aarch64 on Raspberry pi 4B 4Gb]
Desktop (please complete the following information if applicable): no DE

![Schermata a 2021-12-27 09-40-20](https://user-images.githubusercontent.com/77537820/147453038-08ef7915-b509-47d8-9802-21ec22f86c9e.png)

**Comment by Kovah** [comment]
Hi!
You can't import a .csv file in LinkAce at the moment. The importer only supports .html files which usually come from the browser. 
The .csv export of LinkAce allows to move your bookmarks to other applications.

**Comment by gianter962** [comment]
Hi, the html import works but the list datas are missing
![Schermata a 2022-01-07 21-55-20](https://user-images.githubusercontent.com/77537820/148606371-08e247c2-491e-4129-a980-446e68b9808a.png)

**Comment by Kovah** [comment]
Hi, the importer is not meant to make backups of the complete application, so neither link history, lists and notes are not included. Please use backups of the database instead.

I'll make this more clear in the documentation.

**Comment by madindehead** [comment]
I am currently experiencing this issue when trying to import from a Firefox HTML export of my bookmarks. Same exact error. 

I am running the [production ](https://github.com/Kovah/LinkAce/blob/main/docker-compose.production.yml) Docker Compose file, but I am using Postgres 13. 

I haven't been able to find the correct log to see what's going wrong, but I will keep looking.

**Comment by Kovah** [comment]
You should be able to view all logs under settings in the top right menu and then > system logs

**Comment by madindehead** [comment]
Found the logs, but I'm not seeing an entry for the bookmark import failure.

**Comment by madindehead** [comment]
I have discovered what the issue is. 

Turns out my Firefox bookmarks file is too big to upload into LinkAce. It's 131MB. I have a problem! 

Is it possible for me to just mount a custom `nginx.conf` to get around the upload limit?

**Comment by Kovah** [comment]
You could try the command line importer, which should be capable of handling such large files.
https://www.linkace.org/docs/v1/cli/

**Comment by Kovah** [comment]
If you have anything to add or any question, please re-open the issue.

**Comment by madindehead** [comment]
I tried using the CLI as suggested and I am seeing this error: 

```
In NetscapeBookmarkParser.php line 313:
Allowed memory size of 268435456 bytes exhausted (tried to allocate 137543888 bytes)
```

File is 155MB, but I don't think it's related to that. I use PostgreSQL with my instance of LinkAce.

**Comment by Kovah** [comment]
You could try it with `php -d memory_limit=512M artisan links:import`
