### ISSUE TITLE
Docs: "Setup with SQLite" doesn't contain hint to set "SETUP_COMPLETED=true" in .env file

### ISSUE THREAD

**Issue by WalterFaber** [Kovah/LinkAce#340]
Situation: Docs: "Setup with SQLite" doesn't contain hint to set "SETUP_COMPLETED=true" in .env file

Steps to reproduce:
1. Go through the SQLite setup.
2. The last instruction says "_You can now open LinkAce in your browser and should be able to use the application._"

Actual: The browser shows the setup screen (which doesn't work with SQLite)
Expectation: The browser shows the LinkAce start screen.

Even if the "LinkAce Setup" page says "_Please notice that the browser-based setup only supports MySQL_" I did not understand that hint as a new user and was confused about the setup screen and assumed that this is still part of the setup for SQLite. 

Proposed solution:
In the SQLite setup, there is a section which describes the adjustments of the .env file: "_Replace DB_DATABASE=linkace with DB_DATABASE=/path-to-linkace/database/database.sqlite in your .env file ..._"
I'd recommend to put there an instruction to also set "SETUP_COMPLETED=true" 

Remark:
Also affects Docs for "Setup with PostgreSQL"

**Comment by Kovah** [comment]
Closed in favor of https://github.com/Kovah/LinkAce-Website/issues/25
Thanks for reporting this issue!
