### ISSUE TITLE
404 page not found on deleted link

### ISSUE THREAD

**Issue by gianter962** [Kovah/LinkAce#346]
**Describe the bug**
404 page not found on deleted link

**To Reproduce**
Click on a linck and then choose delete

**Expected behavior**
A redirect on a existent page

**Screenshots**

**LinkAce setup (please complete the following information):**
 - Version: 1.8.0
 - Installed via: docher
 - OS: aarch64 Manjaro
![Schermata a 2022-01-07 21-47-48](https://user-images.githubusercontent.com/77537820/148606904-0e1e0e43-209e-436b-904b-a124582b6b3f.png)

**Comment by Kovah** [comment]
Ah thanks for reporting, seems I missed that in the last release.
