### ISSUE TITLE
Environment value from docker-compose.yml doens't set correct timezone.

### ISSUE THREAD

**Issue by Drallas** [Kovah/LinkAce#348]
**Describe the bug**
If docker-compose.yml contains an environment entry

```
 environment:
    - TZ=Europe/Berlin
```
 
It would be nice if this carries over into the correct location set in LinkAce, without the need to set it manualy.

Perhaps i'm 'spoiled' with other apps doing this!

**Comment by Drallas** [comment]
Skimming trough your code..

app.php has `'timezone' => 'UTC',`, pehaps an option if it can't be retrieved from docker-compose.yml (not sure) to include timezone in .env.

**Comment by Kovah** [comment]
That's a good idea and easily doable. Will be added in 1.9.

**Comment by Kovah** [comment]
It is now possible to set the timezone, however, I discourage to use this as it _can_ has unintended side effects.

**Comment by jimmybrancaccio** [comment]
@Kovah What sort of unintended side effects would there be?

**Comment by Kovah** [comment]
I could imagine that if you set the application timezone to something different than UTC and change the user timezone (in the settings) to something else, it could display the wrong dates and times. I have not tested this, so its just a guess.
