### ISSUE TITLE
Update Docs to Enclose APP_USER_AGENT Value in Quotes

### ISSUE THREAD

**Issue by jimmybrancaccio** [Kovah/LinkAce#351]
**Describe the bug**

It appears if there's a space in the value of an environment variable in the `.env` file it will throw and error when running something like `php artisan config:clear`. I did a quick Google to ensure this is true and [found this](https://stackoverflow.com/questions/43639440/artisan-command-says-dotenv-values-containing-spaces-must-be-surrounded-by-quo) as well as it's [noted in the Laravel docs](https://laravel.com/docs/8.x/configuration#environment-variable-types).

**To Reproduce**

I am currently using the Docker deployment, but this should replicate by using any deployment method.

1. Update or install LinkAce using 1.9 where 'APP_USER_AGENT' is available. Alternatively you could probably just set any of the environment variables in the `.env` to have a value where there's a space in it (ex., `APP_NAME=My Cool Bookmarks!`.
2. Bring the container up.
3. Attempt to run `php artisan config:clear`.
4. Observe an error message that should look something like:
    ```
    The environment file is invalid!
    Failed to parse dotenv file. Encountered unexpected whitespace at [Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15].
    ```

**Expected behavior**

I would have expected that there would be no issues when running `php artisan config:clear`.

**Screenshots**

N/A

**LinkAce setup (please complete the following information):**

- Version: 1.9
- Installed via: Docker
- OS: Ubuntu 20.04.3

**Desktop (please complete the following information if applicable):**

N/A

**Smartphone (please complete the following information if applicable):**

N/A

**Additional context**

You may be wondering why I ran `php artisan config:clear` and this is because I ran through the [normal upgrade steps](https://www.linkace.org/docs/v1/upgrade/), started up my container, _and then_ I edited my `.env` file on my Docker host system. Since I did that, I then had to run the artisan command in order for the changes I made to the `.env` file to take effect.

All that needs to be done here is to [update the documentation page](https://www.linkace.org/docs/v1/configuration/system-settings/#advanced-system-settings) so that the example uses quotes, such as:

```
APP_USER_AGENT="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
```

**Comment by Kovah** [comment]
Thanks, documentation was updated 👍 
https://www.linkace.org/docs/v1/configuration/system-settings/#app_user_agent
