### ISSUE TITLE
Choosing an auto-completed tag or list doesn't remove the typed charachters anymore

### ISSUE THREAD

**Issue by jk** [Kovah/LinkAce#378]
**Describe the bug**
Since version 1.9.0 there was a bug introduced, where when I'm typing the first few letters of a already defined tag or list and choose one from the auto-completed dropdown, the typed chars weren't removed afterwards and I have to manually delete it. 

**To Reproduce**
1. Add a link via bookmarklet from the browser
2. Focus the `Tags` or `Lists` text area
3. Type the first few letters of an already existing Tag or List
4. Choose an auto-completed menu item from the appearing drop down menu via enter/return/mouse click.

**Expected behavior**
Behavior should revert to pre-1.9.0 where the already typed letters were removed when selecting an auto-completed suggestion.

**Screenshots**
![Tag auto-completed chars werent removed](https://user-images.githubusercontent.com/40043/151768784-72a0d11e-7230-4fe0-8915-e23ee0fa5db5.gif)

**LinkAce setup (please complete the following information):**
 - Version: 1.9.1
 - Installed via: Docker behind Traefik 2.x
 - OS: Ubuntu

**Desktop:**
 - OS: macOS 12.2
 - Browser: Firefox 96.0.3 & Safari 15.3

**Comment by Kovah** [comment]
I noticed that too, although I wouldn't label it as a bug right now because (at least when I tested it) the remaining letters go away once you click outside the tag field or press tab. I'll see if there's some configuration option for that in the new library I am using for the tag and list search.

**Comment by andy47** [comment]
I'm seeing this on a fresh install (docker compose) and using Firefox to access the site. The remaining letters do disappear when I click out of the field but the conventional behaviour is that they disappear when you select an element from the drop down list - which is definitely my preference.
