### ISSUE TITLE
Backups are going to "/app/storage/app/LinkAce" directory

### ISSUE THREAD

**Issue by milindpatel63** [Kovah/LinkAce#381]
I am running linkace in docker advanced mode...

i have enabled backups and mapped the /app/storage/app/backups folder to my host...

now whenever the run the command

php artisan backup:run

the backups zip files are saving into the path /app/storage/app/LinkAce inside the container....
how do I specify the path to which backups should go? Any env variable?

Also, in the docker example yml file at https://github.com/Kovah/LinkAce/blob/main/docker-compose.production.yml
Backup path is /app/storage/app/backups

While in the example env file at https://github.com/Kovah/LinkAce/blob/main/.env.docker.production
Backup path written in comment is /storage/app/backups

And mine are going to a whole diff directory 😅

I have mapped the LinkAce directory to my host for now, hope this directory doesn't change in the future.

**Comment by Kovah** [comment]
I have found the issue. The `BACKUP_DISK` configuration in the .env file is wrongly documented. It should be `BACKUP_DISK=local_backups` instead of `BACKUP_DISK=local`.
