### ISSUE TITLE
The public/private link flag changes after import/export using html

### ISSUE THREAD

**Issue by pVlady** [Kovah/LinkAce#394]
**Describe the bug**
1. After export of links into html file (I used sqlite before) and export them into the new clear application (I use mysql now) all public links became private and all private links became public.
2. There are now any lists after import. All lists disappear.

**To Reproduce**
1. Import links into html file.
2. Install application.
3. Import links back.

**Expected behavior**
The link status has not to be changed after export/import operation.
The lists have to be saved after export/import operation.

**Screenshots**

**LinkAce setup (please complete the following information):**
 - Version: 1.9.1
 - Installed via: manual server installation without Docker
 - OS: CentOS 8.5

**Desktop (please complete the following information if applicable):**
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version  98.0.1108.43 64-bit

**Smartphone (please complete the following information if applicable):**

**Additional context**

**Comment by Kovah** [comment]
Sorry to say this, but all that data is lost, if you don't have any backup of the old database.

I just updated the export documentation with an alert that exporting is absolutely not intended to be a _backup_ for LinkAce. In the future, please use the database backups for this.
See https://www.linkace.org/docs/v1/configuration/export/

**Comment by pVlady** [comment]
Thanks for your answer.
There is no problem with my data — I backup it regulary.
This way I tried to migrate from sqlite to mysql database.
 
Best regards,
Vlady.
 
P.S. Your app is great!
