### ISSUE TITLE
Delete a link and after add again the same link

### ISSUE THREAD

**Issue by gianter962** [Kovah/LinkAce#400]
**Describe the bug**
If you delete a link and after try to add again the same link you will get "The url has already been taken" ... obviously if you search for that link you will not find it because it has been deleted.
Unfortunately the deleted url is remained as record in the table called "links" so if you want add again the same link you have to delete it manually from the table. --- >> linkace v1.9.1
Please look at pics
![Schermata a 2022-02-20 18-30-37](https://user-images.githubusercontent.com/77537820/154856389-45ec0106-e049-4e2f-8e79-f116ae3e0750.png)
![Schermata a 2022-02-20 18-30-55](https://user-images.githubusercontent.com/77537820/154857118-e88dc752-b6e2-4e12-a914-6d86cf8b8fd6.png)

**Comment by Kovah** [comment]
LinkAce has a trash feature.
https://www.linkace.org/docs/v1/application/trash/

May I ask what can be done to make this more clear? Too many people already missed this, despite there already is a trash icon in the main navigation.
