### ISSUE TITLE
"Simple" Docker container should carry out steps that are currently manual

### ISSUE THREAD

**Issue by gingerbeardman** [Kovah/LinkAce#404]
**Is your feature request related to a problem? Please describe.**

The "simple" Docker installation is... not simple.

I generated the key but couldn't figure out the .env file so I had to give up. 
I thought it worth reporting this barrier to entry.

Compared to the many other docker containers I've installed, the setup here requires far too much manual input. 
Can the key generation, copying of the .env, etc not be automated as part of the docker first run?

**Describe the solution you'd like**

Preset configuration. No manual input to bring up the container.

**Describe alternatives you've considered**

- LinkDing (will probably use this)
- Shaarli (not for me)

**Comment by Kovah** [comment]
Hi, totally understand your point. The setup process is quite a mess at the moment and definitely needs some attention.

This was already discussed in #398, so I am closing this issue in favor of the existing one. If you would like to follow the discussion, please watch the existing issue.
