### ISSUE TITLE
Typo in DE_de/trash.php?

### ISSUE THREAD

**Issue by Systemsemaphore** [Kovah/LinkAce#414]
**Describe the bug**

I suppose there is a typo "Löschte Links" in trash.php

**To Reproduce**
1. Click on trashcan icon (top right)
2. It says "Löschte Links" right there

see lines 7-10 of resources/lang/de_DE/trash.php as well

`'deleted_links' => 'Löschte Links',`
`'deleted_lists' => 'Gelöschte Listen',`
`'deleted_tags' => 'Gelöschte Tags',`
`'deleted_notes' => 'Gelöschte Notizen',`

**Expected behavior**

Surely it's meant to say **Gelöschte** Links instead of **Löschte** Links (?)

**Screenshots**

![linkace_typo](https://user-images.githubusercontent.com/74195074/158451936-6a6cfbaa-4445-4f62-94b8-6939e4ca3b10.PNG)

**LinkAce setup (please complete the following information):**
 - Version: [e.g. 1.9.2]

Not trying to be pedantic, just noticed and thought I'd leave a quick comment. LinkAce is awesome!

**Comment by Kovah** [comment]
Thanks, saolved in #415
