### ISSUE TITLE
500 error when viewing web interface for the first time

### ISSUE THREAD

**Issue by gingerbeardman** [Kovah/LinkAce#429]
**Describe the bug**
500 error when viewing web interface for the first time

**To Reproduce**
1. read the new, simpler instructions (thank you!)
1. install using docker https://www.linkace.org/docs/v1/setup/setup-with-docker/simple/
1. go to web interface

**Expected behavior**
- web ui should show something other than an error

**Screenshots**
<img width="1080" alt="Screen shot 2022-04-04 at 17 02 00" src="https://user-images.githubusercontent.com/49612/161584908-e02f97a0-398e-4f2f-8806-8bf5821ffaab.png">

**LinkAce setup (please complete the following information):**
 - Version: 1.10.0
 - Installed via: Docker
 - OS: Linux (Synology)

**Desktop (please complete the following information if applicable):**
 - OS: macOS
 - Browser: Safari
 - Version: 15.4 (17613.1.17.1.13)

**Additional context**
- No errors in the logs, just successful web requests
- I changed the default local port from 80 to 5678 because the container would not come up as port 80 was already in use on my system. Container port is still 80.
```
    ports:
      - "0.0.0.0:5678:80"
```

**Comment by gingerbeardman** [comment]
This was due to .env permissions, they were:

```
-rwxrwxrwx+ 1 admin users   809 Apr  4 16:54 .env
```

I did `chmod 666 .env` to get

```
-rw-rw-rw-  1 admin users   809 Apr  4 16:54 .env
```

...and now it works!

Why are the previous permissions not workable?

**Comment by Kovah** [comment]
Not sure why 0777 did not work, the .env file just needs to be writable. 
However, good to hear that it worked and thanks for trying LinkAce again. 😊

**Comment by Timmer2021** [comment]
I get the same error as the OP, in fact the same setup on a synology DS918.. 

Can't get past the initial 500 error for the life of me.. I've tried the chmod 666 but still no go.. Any other ideas?

Thanks in advance. 
Tim.

**Comment by Kovah** [comment]
Have you generated the Application Key as mentioned in the setup?

**Comment by sbhal** [comment]
I had same error on synology. I resolved it by giving 777 permissions to mounted logs dir.
