### ISSUE TITLE
New display type to be closer to Pinboard

### ISSUE THREAD

**Issue by gingerbeardman** [Kovah/LinkAce#433]
**Is your feature request related to a problem? Please describe.**
I have come from using pinboard for 11 years so my usage patterns are embedded in muscle memory.

My expectations are that the same sort of information should be viewable in the same sort of footprint.

Currently "list with many" means few bookmarks are visible.
And "list with less" does not show all information.

**Describe the solution you'd like**
- ideally a new list type that shows the same information as Pinboard, in a similar footprint
- or that could be:
  - "list with less details" but with tags
  - "list with many details" but without images
  - separate thumbnail toggle

**Describe alternatives you've considered**
- pinboard
- linkding (it was easy to add URL display to the default list style)
- Shaarli (needed some heavy editing or custom theme to get a good display)

**Additional context**

### Pinboard
- private/read (using colour only)
- star
- title
- url
- description
- tags
- date
- edit/delete
- (everything being left aligned is a perfect reading experience)
<img width="647" alt="Screen shot 2022-04-04 at 17 37 03" src="https://user-images.githubusercontent.com/49612/161591025-566fe1bb-6f3b-4048-a268-ba7fc19cd6c9.png">

### LinkAce "list with less details"
- private/read (using icon only)
- site icon
- title
- url
- (mix of left/right alignment makes a difficult reading experience)
<img width="954" alt="Screen shot 2022-04-04 at 17 37 13" src="https://user-images.githubusercontent.com/49612/161591057-0cadcd5a-bf4d-45d0-8876-88bf1db94987.png">

### LinkAce "list with many details"
- image
- private/read (using icon only)
- site icon
- title
- url
- description
- tags
- date
- edit/delete
- (mix of left/right alignment makes a difficult reading experience)
<img width="953" alt="Screen shot 2022-04-04 at 17 37 36" src="https://user-images.githubusercontent.com/49612/161591067-29191561-a5b8-4f1b-8a5a-ba53a23a44b6.png">

## Related issues
- #430
- #431
- #434 
- #435

**Comment by gingerbeardman** [comment]
Using the tip in #436 

A tremendous hack, but this is what I have:

```
<style>
:root, body {
--bs-body-font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
}

#app > main > section > div > div > div.card-body.py-2 > div > div.col-12.col-sm-6.d-sm-flex.align-items-sm-center.justify-content-sm-end.flex-wrap > div.btn-group.mt-1.ms-md-2 svg,
#app > main > section > div > div > div > div > div.d-flex.me-2.mw-100.order-2.order-md-1 > div.me-2.me-lg-3,
.text-pale,
.card-body > div > div:nth-child(1) > div,
.link-thumbnail-list-holder {
display: none;
}

.row > div {
width: 100%;
}

.row .justify-content-sm-end {
justify-content: flex-start !important;
}

.link-wrapper .mb-4 {
margin-bottom: -1px !important;
}

.card-body {
padding-bottom: 0;
}

.card-body.py-2 {
padding-top: 0 !important;
}

#app > main > section > div > div > div.card-body.py-2 > div > div.col-12.col-sm-6 > div:nth-child(2) .btn-light {
background: none !important;
border: none !important;
white-space: nowrap; 
overflow: hidden;
}

#app > main > section > div > div > div.card-body.py-2 > div > div.col-12.col-sm-6 > div:nth-child(2) > a:nth-child(1).btn-light {
width: 2.5rem;
}

#app > main > section > div > div > div.card-body.py-2 > div > div.col-12.col-sm-6 > div:nth-child(2) > a:nth-child(2).btn-light {
width: 1.9rem;
}

#app > main > section > div > div > div.card-body.py-2 > div > div.col-12.col-sm-6 > div:nth-child(2) > button.btn-light {
width: 2.9rem;
}

#app > main > section > div > div > div.card-body.py-2 > div > div.col-12.col-sm-6.d-sm-flex.align-items-sm-center.justify-content-sm-end.flex-wrap > div.text-xs {
padding-top: 0.25rem;
}
</style>
```

<img width="1080" alt="Screen shot 2022-04-05 at 10 54 30" src="https://user-images.githubusercontent.com/49612/161728962-19e08381-cb1a-42d7-accf-3a9875f73af5.png">

**Comment by gingerbeardman** [comment]
Even more like Pinboard.

## CSS

```
<style>
:root, body {
--bs-body-font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
}

#app > main > section > div > div > div.card-body.py-2 > div > div.col-12.col-sm-6.d-sm-flex.align-items-sm-center.justify-content-sm-end.flex-wrap > div.btn-group.mt-1.ms-md-2 svg,
#app > main > section > div > div > div > div > div.d-flex.me-2.mw-100.order-2.order-md-1 > div.me-2.me-lg-3,
.text-pale,
.card-body > div > div:nth-child(1) > div,
.link-thumbnail-list-holder {
display: none;
}

.row > div {
width: 100%;
}

.row .justify-content-sm-end {
justify-content: flex-start !important;
}

.link-wrapper .mb-4 {
margin-bottom: -1px !important;
}

.card-body {
padding-bottom: 0;
}

.card-body.py-2 {
padding-top: 0 !important;
}

#app > main > section > div > div > div.card-body.py-2 > div > div.col-12.col-sm-6 > div:nth-child(2) .btn-light {
background: none !important;
border: none !important;
white-space: nowrap; 
overflow: hidden;
}

#app > main > section > div > div > div.card-body.py-2 > div > div.col-12.col-sm-6 > div:nth-child(2) > a:nth-child(1).btn-light {
width: 2.5rem;
}

#app > main > section > div > div > div.card-body.py-2 > div > div.col-12.col-sm-6 > div:nth-child(2) > a:nth-child(2).btn-light {
width: 1.9rem;
}

#app > main > section > div > div > div.card-body.py-2 > div > div.col-12.col-sm-6 > div:nth-child(2) > button.btn-light {
width: 2.9rem;
}

#app > main > section > div > div > div.card-body.py-2 > div > div.col-12.col-sm-6.d-sm-flex.align-items-sm-center.justify-content-sm-end.flex-wrap > div.text-xs {
padding-top: 0.25rem;
}

.card {
border: none;
}

.card-body {
padding: 1rem 0 0 0;
}
</style>
```

## Screenshot
<img width="1080" alt="Screen shot 2022-04-05 at 11 13 31" src="https://user-images.githubusercontent.com/49612/161732203-ca5d218c-b121-4b3c-a180-204363719d88.png">

**Comment by gingerbeardman** [comment]
I'm happy to offer my services, for free, to adding this new style officially.

**Comment by Kovah** [comment]
I guess the styling options will be completely redone in the next big version. I am not happy with the current versions.

**Comment by powellc** [comment]
Oh, this is a tremendous hack while the styles are redone. Thank you @gingerbeardman and thank you @Kovah for a great project!

**Comment by Kovah** [comment]
Should be completed with #553
