### ISSUE TITLE
Custom/user CSS setting?

### ISSUE THREAD

**Issue by gingerbeardman** [Kovah/LinkAce#436]
**Is your feature request related to a problem? Please describe.**
It's difficult to get a display style to my preference with the built-in styles

For example I'd prefer everything in a list to be left aligned so I can easily read down a single column.

**Describe the solution you'd like**
A "user css" setting might go some way to solve this?

- add custom css setting
  - raw CSS
  - or URL

**Describe alternatives you've considered**
- Pinboard
- linkding
- Shaarli

**Comment by Kovah** [comment]
You could add custom styles to the Custom Header Content under system settings like
```html
<style>
// you custom styles
</style>
```
It should override all other styles.
