### ISSUE TITLE
Semantic classes on elements to allow easier custom styling

### ISSUE THREAD

**Issue by gingerbeardman** [Kovah/LinkAce#437]
**Is your feature request related to a problem? Please describe.**

Custom styling is tricky because the only classes used are from bootstrap

**Describe the solution you'd like**

Semantic classes applied to:
- card
- title
- link
- tags
- tag
- date
- private
- to-read
- show, edit, delete
- etc

And also:
- page type (so I can style elements only on the All Links page)

**Describe alternatives you've considered**

- Pinboard
- linkding
- Shaarli

**Additional context**

- See #433

**Comment by Kovah** [comment]
I added quite a lot of semantic ans otherwise suitable classes to all different parts of the application.
Due to the sheer size, not all elements got any describing classes, but I hope this helps a lot with custom styling.
