### ISSUE TITLE
URL to be truncated in CSS rather than at page render time

### ISSUE THREAD

**Issue by gingerbeardman** [Kovah/LinkAce#441]
**Is your feature request related to a problem? Please describe.**

When doing user styles, I noticed that long URLs are truncated whilst generating the page

Doing this hides the full URL and affects accessibility.

**Describe the solution you'd like**

- leave the full URL in the HTML
- truncate long URLs using CSS

**Describe alternatives you've considered**
- Pinboard
- linkding
- Shaarli

**Comment by Kovah** [comment]
Good point

**Comment by gingerbeardman** [comment]
URL is missing the scheme/protocal (http,https,etc)

**Comment by Kovah** [comment]
Should be completed with #553
