### ISSUE TITLE
Display archived link if original link is dead or moved

### ISSUE THREAD

**Issue by gingerbeardman** [Kovah/LinkAce#444]
**Is your feature request related to a problem? Please describe.**

This is my last issue for now! 😅

A lot of my oldest links are dead, though they may have already been archived on wayback machine.

**Describe the solution you'd like**

- figure out if link is dead or not (404, 30x, etc)
- display archived link in its place

**Describe alternatives you've considered**
- Pinboard
- linkding
- Shaarli

**Thought**

Is an archived link only displayed if it was created by LinkAce? Are previously archived links also displayed @Kovah ?

**Comment by Kovah** [comment]
The archive link is displayed if LinkAce nows that the link is dead, so it should be possible after all links were checked.

**Comment by gingerbeardman** [comment]
Awesome!
