### ISSUE TITLE
Css not rendering after setup

### ISSUE THREAD

**Issue by MadM0d** [Kovah/LinkAce#454]
I'm not an expert nor am I a novice, but I can not seem to get the Css structure to render. I inspected elements and the app.css is being pulled. I am not quite sure what to do from here. I currently have it c=hosted on a DNS server at [slink.news/slinks/public/](slink.news/slinks/public/)

**Comment by Kovah** [comment]
Point your web server to the public directory, not the directory of linkace itself.

**Comment by Kovah** [comment]
Feel free to reopen the ticket if you still have any issues.
