### ISSUE TITLE
 Opening "Settings" end with "500 - Server Error" because of DISPLAY_CARDS_DETAILED

### ISSUE THREAD

**Issue by WalterFaber** [Kovah/LinkAce#459]
**Describe the bug**
 Opening "Settings" end with "500 - Server Error"

**To Reproduce**
1. Select Menue "<Username>" -> "Settings" 
4. See error 500

**Expected behavior**
Settings page opens.

**LinkAce setup (please complete the following information):**
 - Version: 1.10.0
 - Installed via: PHP
 - OS: Arch Linux

**Desktop (please complete the following information if applicable):**
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 99

**Additional context**

I just migrated from 1.9.2 to 1.10.0. Everything else seems to work fine e.g. I can create new links.

Seems to be related to new setting "DISPLAY_CARDS_DETAILED"

System Logs: Error
`Undefined constant App\Models\Link::DISPLAY_CARDS_DETAILED (View: /usr/share/nginx/html/linkace/resources/views/app/settings/partials/user/app-settings.blade.php) (View: /usr/share/nginx/html/linkace/resources/views/app/settings/partials/user/app-settings.blade.php) {"userId":1,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): Undefined constant App\\Models\\Link::DISPLAY_CARDS_DETAILED (View: /usr/share/nginx/html/linkace/resources/views/app/settings/partials/user/app-settings.blade.php) (View: /usr/share/nginx/html/linkace/resources/views/app/settings/partials/user/app-settings.blade.php) at /usr/share/nginx/html/linkace/storage/framework/views/3019762873d8846aa4899b87156417652a0cf453.php:165) `

**Comment by Kovah** [comment]
Could you try to run `php artisan view:clear` and try again?
If it does not work, make sure that app files in the `app` directory are properly replaced with the newer ones.

**Comment by WalterFaber** [comment]
Hi Kevin,

issue can be closed - it is fixed.

Even though "php artisan view:clear" did not help, it pointed me to the right direction. Flushing the PHP OPcache fixed it. I usually do that, but the OPcache path has changed (not related to linkace) and hence I didn't flush the OPcache correctly.

Thank you again for your quick support and your efforts with the software.
