### ISSUE TITLE
The URL has already been taken."

### ISSUE THREAD

**Issue by dtypo** [Kovah/LinkAce#461]
**Description**
When re-adding a link that has been previously deleted, che system gives the following error: "The URL has already been taken".

**To Reproduce**
1. Add a link of your choice
2. Delete the previously added link
3. Try to add again the same link

**Expected behavior**
The system shoul allow to re-add the link.

**Screenshots**
![image](https://user-images.githubusercontent.com/40309637/165352240-087740bb-79c4-433c-865e-c30ed67b0594.png)

**LinkAce setup (please complete the following information):**
 - Version:  v1.10 (simple version)
 - Installed via: Docker-compose
 - OS: DSM 7.0.1-42218 Update 3

**Comment by Kovah** [comment]
See https://www.linkace.org/docs/v1/application/trash/
