### ISSUE TITLE
docker tag issue with linkace/linkace:php-nginx

### ISSUE THREAD

**Issue by doc-jay** [Kovah/LinkAce#469]
**Describe the bug**
When using the tag 'linkace/linkace:php-nginx', and the example in the docker advanced configuration [here](https://www.linkace.org/docs/v1/setup/setup-with-docker/advanced-configuration/), the example calls for ports to be listening inside of docker with '8080'.  
example:  "0.0.0.0:80:8080"

I kept getting a 404 when I went to test the container, and I found that in nginx, inside the container, it was only listening on port 80 in the /etc/nginx/http.d/default.conf file.

I changed my port inside the container to listen on port 80 and I could then access linkace sucessfully from port 8017 outside of docker.

this might affect other tags and other docker-compose examples in your docs.

Sharing what I have found, thank you for sharing your project!

Here is a copy of my docker-compose.yml file

`version: "3"
services:
  app:
    image: linkace/linkace:php-nginx
    container_name: linkace
    restart: unless-stopped
    networks:
      sycdock_net:
        ipv4_address: 172.20.0.16
    ports:
      - "0.0.0.0:8017:80"
    environment:
      - APP_KEY=my key here
      - SETUP_COMPLETED=false
      - DB_HOST=my external DB host outside of docker
      - DB_DATABASE=linkace
      - DB_USERNAME=linkaceuser
      - DB_PASSWORD=mysql linkace db password
    volumes:
      - /opt/docker/docker_data/linkace-data/linkace.conf:/opt/docker/etc/nginx/conf.d/linkace.conf:ro

networks:
  sycdock_net:
    external: true`

**Comment by Kovah** [comment]
Thanks for the heads up, will check that soon.

**Comment by Kovah** [comment]
I corrected the documentation
