### ISSUE TITLE
Setup with Docker (Advanced) incomplete

### ISSUE THREAD

**Issue by denis-ev** [Kovah/LinkAce#470]
**Describe the bug**
I've just tried to setup with docker (advanced) and the config says to leave the app_key empty (# The app key is generated later, please leave it blank), but there is no information about generation the app_key in the docs.
https://www.linkace.org/docs/v1/setup/setup-with-docker/advanced/ 

Needed to run `docker-compose exec app php artisan key:generate` and then `docker-compose exec app php artisan migrate` otherwise it was only showing a white page and no errors.

Please add missing step to the docs.

**Comment by Kovah** [comment]
Hi Denis, the documentation is not incomplete as the key is generated on the first run and the database is migrated in the built-in setup. Please just follow the documentation.

Please note that the docs are only valid for the last stable version of LinkAce.
