### ISSUE TITLE
"Operation timed out" for almost every (even successful) web.archive.org save

### ISSUE THREAD

**Issue by BBaoVanC** [Kovah/LinkAce#472]
**Describe the bug**

If I look at my Laravel logs, I see tons of errors that look like this:

```text
cURL error 28: Operation timed out after 10000 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://web.archive.org/save/https://github.com/adityatelange/hugo-PaperMod {"userId":1,"exception":"[object] (Illuminate\\Http\\Client\\ConnectionException(code: 0): cURL error 28: Operation timed out after 10000 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://web.archive.org/save/https://github.com/adityatelange/hugo-PaperMod at /var/www/linkace.bbaovanc.com/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php:710) 
```

This is happening for almost every single link I save. But if I go to the link and click "Link archive @ Wayback Machine", I can see an archive was saved at the exact time and date that I saved the link on Linkace. So even though the request timed out, archive.org still saved the snapshot.

**To Reproduce**

1. Save a few links using Linkace
2. Check Laravel logs

**Expected behavior**

If there isn't some underlying issue that can be done on Linkace's end to prevent the timeout, maybe there could be some way to verify that a snapshot was properly saved before logging an error? It really clutters up my logs and makes them hard to find actual errors in.

**Screenshots**

![image](https://user-images.githubusercontent.com/17971474/169634850-7ccf632e-7441-4b30-bda9-333302999fcb.png)

**LinkAce setup (please complete the following information):**

 - Version: 1.10.1
 - Installed via: php-fpm and Caddy webserver
 - OS: Debian 11

**Desktop (please complete the following information if applicable):**

 - OS: Arch Linux
 - Browser: Firefox 100
 - Version: Latest

**Comment by Kovah** [comment]
Hm yeah, i'll see if I can bump the timeout a bit or find another solution. Sadly, the Internet Archive has no real API to save websites so you have to trigger the saving by opening an URL and wait until the Archive saved the website successfully (which can take a while depending on the current load and the website size).
