### ISSUE TITLE
Can't install with docker advanced setup

### ISSUE THREAD

**Issue by BENETNATH** [Kovah/LinkAce#480]
Hello,
I've just spent 1 hour to try to set LinkAce up. Sadly, it's a failure..
Either with simple or advanced, it's the same.
With the advanced, i just took the files, removed the key in the app_key field to leave it blank after the equal.
and everything goes well, no error in the process.
Container are well created, displayed as working in Portainer, but i get an error 500 when I try to connect.
![image](https://user-images.githubusercontent.com/1931820/172153209-e0148edd-e2d1-4623-93d1-731b46766401.png)

What could be wrong ?

**Comment by Kovah** [comment]
Have you checked these related issues?
- #429
- #299

Also, please check if there are any logs: 
```
docker exec linkace_app_1 ls /app/storage/logs
docker exec linkace_app_1 cat /app/storage/logs/laravel-2022-06-06.log
```

**Comment by BENETNATH** [comment]
I had to generate the key.
But this info is nowhere in the doc i read for advanced setup !
thanks for replies
It's working now

**Comment by Kovah** [comment]
Will check this, key should automatically be generated if its not set. Is it possible that your .env file is not writable before you started LinkAce containers?

**Comment by BENETNATH** [comment]
may be, not sure about that. I've spent really too much time on that ;)
