### ISSUE TITLE
Import Vietnamese package from crowdin

### ISSUE THREAD

**Issue by saosangmo** [Kovah/LinkAce#483]
I have completed translating LinkAce into Vietnamese.
Please consider to pull it.
Thank for you nice tool.

**Comment by Kovah** [comment]
Thanks for the work! However, LinkAce as a word was translated which is not correct. It should stay as it is.

**Comment by saosangmo** [comment]
I used Danh Bạ Tốt, a common term, it like "Good Bookmark in Vietnamese. Now, I have replaced all of them to 'LinkAce'
