### ISSUE TITLE
Add dropdown menu for known lists

### ISSUE THREAD

**Issue by deffcolony** [Kovah/LinkAce#490]
**Is your feature request related to a problem? Please describe.**
Its a problem when you don't remember the list you made... right now you have to guess it or going back to all lists

**Describe the solution you'd like**
Add a dropdown menu for lists. currently it does not show all lists you have made. 

**Additional context**

![this](https://i.imgur.com/ZNon4Ab.png)

![andthis](https://i.imgur.com/ruoqRL4.png)

**Comment by Kovah** [comment]
Thanks for your suggestion! This is related to #270 so you might want to follow this too.

**Comment by MAngel666** [comment]
+1

**Comment by Kovah** [comment]
This will be solved with version 2.0 releasing soon. See #553
