### ISSUE TITLE
Clarify php artisan tasks run by cron

### ISSUE THREAD

**Issue by c-erb** [Kovah/LinkAce#492]
I want to run the tasks normally run by cron with a systemd service that executes the docker commands. What exactly is run by the cron setup?

Something like this?

php artisan links:check
php artisan backup:run

**Comment by martadinata666** [comment]
I want ask some questions, on env `BACKUP_ENABLED=true` it should be enable schedule automatically? or i need to run something with php artisan? I usually use `cron` to do `docker exec linkace php artisan backup:run` rather use internal scheduler. 🤔

**Comment by c-erb** [comment]
Alright. Thank you. Would you say then the best way if I want to use systemd instead of cron would be to schedule the wget cron command with a systemd service and timer?
