### ISSUE TITLE
2FA: Scanning the QR-Code doesn't work

### ISSUE THREAD

**Issue by tohn** [Kovah/LinkAce#501]
**Describe the bug**
I can't seem to scan the (SVG-)QR-Code when enabling 2FA.

**To Reproduce**
1. Go to https://linkace.example/settings
2. Click on 'Enable Two Factor Authentication'
3. Scan the QR-Code with an app (I tried with [Aegis](https://github.com/beemdevelopment/Aegis) and [Binary Eye](https://github.com/markusfisch/BinaryEye))
4. Nothing happens

**Expected behavior**
When scanning the QR-Code, the (Android) App should react.

**Screenshots**
Sorry, I can't publish my QR-Code here :wink:

**LinkAce setup (please complete the following information):**
 - Version: v1.10.2
 - Installed via: Docker
 - OS: ArchLinux

**Desktop (please complete the following information if applicable):**
 - OS: macOS 12.4
 - Browser: Vivaldi
 - Version: 5.3.2679.61

**Smartphone (please complete the following information if applicable):**
 - Device: Xiaomi Redmi Note 7 Pro
 - OS: Android

**Additional context**
When taking the provided alternative link and generating a QR-Code with this, the output looks different, but it works in Aegis and BinaryEye (even this "picture" below should work):

```bash
echo -n "otpauth://totp/LinkAce:mail%40linkace.example?secret=DJQ86QAQ1RLLINKA&issuer=LinkAce&algorithm=SHA1&digits=6&period=30" | qrencode -tutf8
█████████████████████████████████████████████████
█████████████████████████████████████████████████
████ ▄▄▄▄▄ █▀ ██▄ ▀██▄ ▄ ██▄▀█▄▀▀▀ ▄▄█ ▄▄▄▄▄ ████
████ █   █ █▀▀█ █▄▀  █ █  ▄ █▄█ ▄ ▀  █ █   █ ████
████ █▄▄▄█ █▀ █▀███ ▀▀ ▀▀  ▀ █ ▀█ ▀▄██ █▄▄▄█ ████
████▄▄▄▄▄▄▄█▄▀▄▀ ▀▄▀▄█▄█▄▀ ▀▄█▄▀ █▄▀ █▄▄▄▄▄▄▄████
████▄   ▄█▄  ▄▄█▀▄▄ ▀▄█ ▀▀    ▀▄██▀▀▀▄▀ ▀▄█▄▀████
████▀█▀█▄ ▄█▀ █▀▀█▀▄▄█ ▀▄▀▀██▀█ ▀ ██▄█▀ █▀█▄▄████
████▀▀▀█▄▄▄▀██ ▄▄▀▀ ▀█ █▄█▀█▀█▀██▄▄ ▄▄▀▄██ ▄ ████
█████ ▀▄▄▄▄██▀  ▄▄▄█▀▄  ▀ █▄▀██▀▄█▄▄█▀█▀ ▄▀▀█████
████▀ ▄  ▀▄ █▀▄▄▀▀█▀▄ ▀  █▄ ▄▄▄█▀ ▀▀▀▀▀█▀▄▄█▀████
██████▀▄  ▄▄█▄▀▀  ▄▀▀ ▀▀  █▀▀▄▀ ▄█▄█▀██ █ █ ▄████
█████▄█  ▀▄▄▄▄▄█▀█▄▀▄█▀▄▄▀▀▀▀ ▀██▄▄ ▄  ▄▀▄ █▀████
█████▄█ ▄ ▄▀  ██▀▀▄ ▄██▀█ ▀▀ █▄█▀▄▄▀▄█ ▀▀█ █▀████
████▄█▄▀▄█▄ ▄▀▄▀███  ▄█▀▄▀▄ ▄▄▄█▀▄▀█▀█▀█▀ ▄█ ████
████▀▄▀▄▄▀▄▀▄█▄█▄█▀▄██▄█ ███▀▄█ ▄▀▀▀  ███ █▄▀████
████ █▀▀█▄▄   ▀▄▄█▀ ▀█▄▀▄█▀▀▀ ▀ ▄▄▄▄▄▄ ██▄▄ ▀████
████ █ ▄▄█▄▄ ▀▀ ▄  █▀█▀    ▄▄█▀█▀██ █▀█▀██ ██████
████▄██▄▄▄▄▄▀ ▀▄█▀█▀█ ▄▀▀█ ▀▄▄▄▄▀ ▄█ ▄▄▄  ▄██████
████ ▄▄▄▄▄ █▄▀▀█  ▄▀█ ▀█▀ ▀▀▀▀▄  ▄ ▄ █▄█ ▀█ ▄████
████ █   █ █ ▄ █▀▀▄ ▄▀▀ ▄▀▀ ▀ ▀█▄ ▄█▄▄▄ ▄█ ▄ ████
████ █▄▄▄█ █  ▄█▀▀▄ ▄██▄▀ █ ▀▄▄ ▀▄ ▀▀▀▄█ ▄█ █████
████▄▄▄▄▄▄▄█▄▄████▄▄█▄▄███▄█▄▄▄▄█▄██▄████▄███████
█████████████████████████████████████████████████
█████████████████████████████████████████████████
```

**Comment by Kovah** [comment]
Thanks for the detailed report, will have a look as soon as possible.

**Comment by tohn** [comment]
I think I figured it out: it's the dark mode I was using. Apparently the QR Code needs a small white border around the code to work. If I'm using light mode, it works instantaneously.

This works:

<img width="82" alt="Screenshot 2022-11-17 at 21 02 09" src="https://user-images.githubusercontent.com/427159/202549405-e18e56ae-a109-4209-9ec5-ff82df57d632.png">

This doesn't work:

<img width="89" alt="Screenshot 2022-11-17 at 21 02 48" src="https://user-images.githubusercontent.com/427159/202549410-0bcf3dc5-2acb-48c8-a87a-5e34f84f7438.png">

**Comment by Kovah** [comment]
Interesting, that's a good point. Will try that out and add a border for the code.

**Comment by Kovah** [comment]
Border was added, should be working now in dark mode.
