### ISSUE TITLE
All new links are private

### ISSUE THREAD

**Issue by fethomm** [Kovah/LinkAce#504]
**Describe the bug**
All links are created as private, even though settings are set to no.
**To Reproduce**
1. Go to the website you want to create a link from
2. Click on the browser add-on for LinkAce, fill in what you need and save.
3. Go to LinkAce web interface and find the  new link has a lock to it. Check your settings again to find out, it clearly says 'no' for private links.

**Expected behavior**
I expect links to not be private as st in the settings.
**Screenshots**

**LinkAce setup (please complete the following information):**
 - Version: v1.10.1
 - Installed via: Docker
 - OS: Ubuntu

**Desktop (please complete the following information if applicable):**
 - OS: siduction (Debian Sid)
 - Browser: Chrome
 - Version: 102.0.5005.115

**Smartphone (please complete the following information if applicable):**

**Additional context**
![linkace2](https://user-images.githubusercontent.com/15143037/178047208-0b471615-09e5-4730-b553-ef71c45b9fdd.png)
![linkace1](https://user-images.githubusercontent.com/15143037/178047211-2e0f7555-0e49-41a1-b30c-09e1c9748e02.png)

**Comment by Kovah** [comment]
Thanks for the report. Does it work to switch the setting for private links to "Yes" and then add some links? Might be something off with the setting here.

**Comment by fethomm** [comment]
Edit: This only happens with the add-on in Chrome. If I add a link directly in the web interface, the settings are honored.

**Comment by fethomm** [comment]
Just tried with the setting on 'yes'. Same thing, new links from the add-on are private, as expected.

**Comment by Kovah** [comment]
To clarify: do you mean the bookmarklet that you can add from the settings, or one of the real add-ons which are listed in the documentation?

**Comment by fethomm** [comment]
It is called 'Yet Another LinkAce Extension'
https://chrome.google.com/webstore/detail/yet-another-linkace-exten/ladekkfhihppgfcjgaimgggecekfhmho

**Comment by fethomm** [comment]
I did not know about the bookmarklet. It does the job right. So I will use it from now on. You can close my bug report, if you like. Thanks for your work. Pleased with LinkAce.

**Comment by Kovah** [comment]
Thanks!
If you have a spare minute, could you open an issue in the repository of the extension? https://github.com/Creling/Yet-Another-LinkAce-Extension
I think that would help the creator of the extension.

**Comment by SamuelBlickle** [comment]
Looks like something with the privacy settings does indeed not work as expected. I set my privacy settings for links to 'Yes' but adding links via the 'Quick Add Link' get added as public. Maybe this issue should be reopened, @Kovah?

**Comment by Creling** [comment]
Well, personally, I preferred all links being private. But, yes, an option for this will be better.

I am working on migrating the extension to chrome extension manifest v3 and such an option will be added in the next release.
