### ISSUE TITLE
How to remove duplicate links

### ISSUE THREAD

**Issue by rsvcoder** [Kovah/LinkAce#505]
I tried to import file, which failed don't know the reason.
Then I tried to re-import file again. it imported some links again, 
(failing of import is separate concern)

Now I have duplicate links ,how can I delete duplicate links?

**Comment by Kovah** [comment]
You can manually delete them or clean the links database table. There's no other way.

**Comment by Kovah** [comment]
Closing this for now as all questions are answered. Feel free to re-open if something is unclear.
