### ISSUE TITLE
Memory Exhaustion

### ISSUE THREAD

**Issue by Riprock** [Kovah/LinkAce#510]
**Describe the bug**
Memory Exhaustion Upon import

**To Reproduce**
1. Import a File that is at least 3.88 MB

**Expected behavior**
To fully import a bookmarks.html file

**Screenshots**
![image](https://user-images.githubusercontent.com/8990377/179374187-c0f5190b-7c31-4372-9ae6-4bdb1dbad64a.png)

**LinkAce setup (please complete the following information):**
 - Version:1 .10.2
 - Installed via:Docker
 - OS:Windows

**Desktop (please complete the following information if applicable):**
 - OS: Windows
 - Browser Firefox
 - Version 11

**Additional context**
The File size that I am trying to import is 
![image](https://user-images.githubusercontent.com/8990377/179374254-11ee1dff-b22d-419c-a847-a83c34a1ebc9.png)

**Comment by Kovah** [comment]
If you have the resources and access to the PHP settings, could you try to set the memory_limit to 500M? Maybe there's a website which returns too much content to be properly handled.

**Comment by Riprock** [comment]
Where would I go find the PHP settings? Sorry Ive never written any PHP before.

**Comment by Riprock** [comment]
Thank you
