### ISSUE TITLE
API Call  - "Get all Links" does not provide all Links.

### ISSUE THREAD

**Issue by andredeseive** [Kovah/LinkAce#515]
Hi Kovah, 

unfortunately the Api call for

curl --request GET \
  --url https://demo.linkace.org/api/v1/links \
  --header 'Authorization: Bearer 123' \
  --header 'Content-Type: application/json' \
  --header 'accept: application/json'

does not provide all links inside of LinkAce.
 
https://linkace.stoplight.io/docs/api-docs/b3A6ODA0OTM5-links-get-all-links <- I use the same command as it is written here 

Unfortunately I am only getting a few link, something like 12 links.

Is there an option to get all links in total?

Best whishes and thank you very much!

André

**Comment by andredeseive** [comment]
Thank you very much! Is there also an option to get the tags as well in the output!

**Comment by Kovah** [comment]
At the moment, tags and lists of al ink can only be accessed by [accessing the link itself](https://linkace.stoplight.io/docs/api-docs/b3A6ODA0OTQx-links-link-details).

**Comment by andredeseive** [comment]
Thank you for your fast support!
