### ISSUE TITLE
500 - Server Error when adding Link with invalid SSL Certs

### ISSUE THREAD

**Issue by lordfiSh** [Kovah/LinkAce#518]
**Describe the bug**
500 - Server Error when adding Link with invalid SSL Certs

**To Reproduce**
1. Go to Add New Link
2. add a Link with a not-valid SSL Certs (eg https://forum.systemera.net/topic/53054-importing-and-converting-files-between-microsoft-microsoft-or-microsoft-steam/)

**Expected behavior**
Get a Error Message that says can't add link since the SSL Cert is not valid (or do it anyway)

**Screenshots**
![image](https://user-images.githubusercontent.com/389680/180636736-4d74bf1b-7a36-4afc-9bfe-ccda58779854.png)

**LinkAce setup (please complete the following information):**
 - Version: 1.10.2
 - Installed via: Docker
 - OS: Ubuntu LTS

**Comment by Kovah** [comment]
Thanks for the report. What is shown in the log files (accessible from "system logs" in the menu)?

**Comment by lordfiSh** [comment]
I didn't see any error in the syslog logs. I removed the Docker Mount to the Logs and restarted. 
Now the Links gets added (and the Error Log can be written) ... fixed for me 👍 need check the Folder Permission of the mounted  logs folder. 

![image](https://user-images.githubusercontent.com/389680/180638780-3a8d36fa-d5fb-44c4-a887-77b059293e62.png)

<html>
<body>


Level | Context | Date | Content
-- | -- | -- | --
error | production | 2022-07-24 08:22:08 | cURL error 28: Resolving timed out after 3035 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://forum.systemera.net/topic/53054-importing-and-converting-files-between-microsoft-microsoft-or-microsoft-steam/ {"userId":1,"exception":"[object] (Illuminate\\Http\\Client\\ConnectionException(code: 0): cURL error 28: Resolving timed out after 3035 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://forum.systemera.net/topic/53054-importing-and-converting-files-between-microsoft-microsoft-or-microsoft-steam/ at /app/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php:711)
warning | production | 2022-07-24 08:22:08 | https://forum.systemera.net/topic/53054-importing-and-converting-files-between-microsoft-microsoft-or-microsoft-steam/: https://forum.systemera.net/topic/53054-importing-and-converting-files-between-microsoft-microsoft-or-microsoft-steam/ is not reachable. cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://forum.systemera.net/topic/53054-importing-and-converting-files-between-microsoft-microsoft-or-microsoft-steam/


</body>
</html>
