### ISSUE TITLE
HTTP 500 when creating links using api

### ISSUE THREAD

**Issue by Creling** [Kovah/LinkAce#552]
### Bug Description

Hi,

When I use the api to create a new link, I receive an HTTP 500 error, yet when I check the dashboard, I see that the link has already been saved  I think t it might be related to the timeout of creating new links? 

In addition, I want to dig a little deeper:
1. Will Linkace crawl the url when creating a new link using api, even if the title has been set?
2. If 1) is true, is it possible to disable such an action since it will cost extra time while creating links. 

versioni: [1.10.4](https://github.com/Kovah/LinkAce/releases/download/v1.10.4/linkace-v1.10.4-docker-simple.zip) with sqlite

### How to reproduce

N/A

### Expected behavior

N/A

### Logs

```shell
N/A
```

### LinkAce version

v1.10.4

### Setup Method

Docker

### Operating System

Linux (Ubuntu, CentOS,...)

**Comment by Creling** [comment]
hello？ @Kovah

**Comment by Kovah** [comment]
Sorry I don't have the time right know to look into this.

**Comment by Kovah** [comment]
So, I just had a quick look at this.
At the moment, there is no way to disable the automated pull of information, as there's a lot of stuff going on besides the title generation.
Could you share more details about the 500 error? If you enable the debug mode in the .env file it should show more information on the error page when adding a link.

**Comment by Creling** [comment]
Hi,

The payload of the request which leads the error is here:

![image](https://user-images.githubusercontent.com/43109504/203055683-60c58366-e4e2-434b-bdea-e407ac1ac760.png)

and I save the debug log corresponding to the errror in CodePen:
https://codepen.io/Creling/pen/ZERvNvO

**Comment by Kovah** [comment]
> Argument #1 ($string) must be of type string, array given

When saving tags or lists for a link via the api, it must be an array of numbers or strings. If you know the IDs of existing tags, pass them as numbers, otherwise pass the tags by their name.
https://linkace.stoplight.io/docs/api-docs/b3A6ODA0OTQw-links-create

**Comment by Creling** [comment]
get it, thanks.
