### ISSUE TITLE
search api doesn't work in some case

### ISSUE THREAD

**Issue by Creling** [Kovah/LinkAce#554]
### Bug Description

Hi Koval,
Suppose I have a link like following:
```url
https://www.reddit.com/r/brave_browser/comments/p70jyh/comment/is9j8lw/?context=3
```
when I search it using following commands:
```bash
curl 'https://foo.com/api/v1/search/links?query=https%3A%2F%2Fwww.reddit.com%2Fr%2Fbrave_browser%2Fcomments%2Fp70jyh%2Fcomment%2Fis9j8lw%2F%3Fcontext%3D3' \
  -H 'authority: foo.com' \
  -H 'accept: */*' \
  -H 'accept-language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6,zh-TW;q=0.5' \
  -H 'authorization: Bearer 9gMg9wt2CZUfEKYUGxJPRNGTMq22CYnG' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'dnt: 1' \
  -H 'origin: chrome-extension://fnmhjneeppolfjjdnkbdhbnbmjkndlmm' \
  -H 'pragma: no-cache' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.42' \
  --compressed \
| jq
```
the search result is empty.

However, if I replace the query text with `https%3A%2F%2Fwww.reddit.com` (the http encode of `https://www.reddit.com`), it returns a correct result.

Could you reproduce it in your end?

Yours, Creling

### How to reproduce

N/A

### Expected behavior

Return a correct result with the search pattern `https%3A%2F%2Fwww.reddit.com%2Fr%2Fbrave_browser%2Fcomments%2Fp70jyh%2Fcomment%2Fis9j8lw%2F%3Fcontext%3D3`

### Screenshots

![image](https://user-images.githubusercontent.com/43109504/196201467-86d3d8ca-5411-40e1-8e66-f44a6e647b63.png)

### LinkAce version

v1.10.4

### Setup Method

Docker

### Operating System

Linux (Ubuntu, CentOS,...)

**Comment by Creling** [comment]
> I just don't understand the explanation about replacing the query with https%3A%2F%2Fwww.reddit.com. Could you explain that more?

I mean that if I search for `https%3A%2F%2Fwww.reddit.com`, the linkice returns a correct result, i.e. a link whose url is `"https://www.reddit.com/r/brave_browser/comments/p70jyh/comment/is9j8lw/?context=3"`

![image](https://user-images.githubusercontent.com/43109504/202438367-8265ff64-2619-4f98-ba0b-9128a908381f.png)

However, if I search for `https%3A%2F%2Fwww.reddit.com%2Fr%2Fbrave_browser%2Fcomments%2Fp70jyh%2Fcomment%2Fis9j8lw%2F%3Fcontext%3D3`, linkace returns null, which is incorrect.

![image](https://user-images.githubusercontent.com/43109504/202439982-dd32e106-795c-409d-bef6-b6ab26e1bb92.png)

**Comment by Kovah** [comment]
I added a link with the url `https://www.reddit.com/r/brave_browser/comments/p70jyh/comment/is9j8lw/?context=3`.

Searching is performed via 
```
curl --request GET \
  --url 'https://example.com/api/v1/search/links?query=https%253A%252F%252Fwww.reddit.com%252Fr%252Fbrave_browser%252Fcomments%252Fp70jyh%252Fcomment%252Fis9j8lw%252F%253Fcontext%253D3' \
  --header 'Authorization: Bearer --redacted---' \
  --header 'accept: application/json'
```
and the response is 
```
{
	"current_page": 1,
	"data": [
		{
			"id": 638,
			"user_id": 1,
			"url": "https:\/\/www.reddit.com\/r\/brave_browser\/comments\/p70jyh\/comment\/is9j8lw\/?context=3",
			"title": "Add vertical tabs feature in Brave like it is present in Microsoft Edge - Desktop Requests : brave_browser",
			"description": "11 votes, 21 comments. 80.7k members in the brave_browser community. The best privacy online. Browse privately. Search privately. Brave is on a …",
			"icon": "brand.reddit",
			"thumbnail": "https:\/\/external-preview.redd.it\/YIvmmsWM9VOA19lRDN2BGJLoME2iU5u-PtQRiKWvyVU.jpg?auto=webp&s=12aea8ef8d789ce46cf6a11fbccfaabccbdbf2bc",
			"is_private": false,
			"status": 1,
			"check_disabled": false,
			"created_at": "2022-11-17T11:21:48.000000Z",
			"updated_at": "2022-11-17T11:21:48.000000Z",
			"deleted_at": null,
			"tags": []
		}
	],
	"first_page_url": "https:\/\/example.com\/api\/v1\/search\/links?page=1",
	"from": 1,
	"last_page": 1,
	"last_page_url": "https:\/\/example.com\/api\/v1\/search\/links?page=1",
	"links": [
		{
			"url": null,
			"label": "&laquo; Previous",
			"active": false
		},
		{
			"url": "https:\/\/example.com\/api\/v1\/search\/links?page=1",
			"label": "1",
			"active": true
		},
		{
			"url": null,
			"label": "Next &raquo;",
			"active": false
		}
	],
	"next_page_url": null,
	"path": "https:\/\/example.com\/api\/v1\/search\/links",
	"per_page": "24",
	"prev_page_url": null,
	"to": 1,
	"total": 1
}
```

**Comment by Creling** [comment]
Get it, it is really strange and seems to be out of our scope.
