### ISSUE TITLE
Dosent work on Synology Docker

### ISSUE THREAD

**Issue by MAngel666** [Kovah/LinkAce#562]
### Bug Description

Container starts and creates the tables in postgres...
If I want to connect it I get 502 error.
(APP_KEY/APP_URL/SETUP_COMPLETED/DB/MAIL are set over Environment Variables)

if I connect to the container and make "wget http://localhost:9000" there, I get:
```
Connecting to localhost:9000 (127.0.0.1:9000)
wget: error getting response: Connection reset by peer
```

So I think there is something wrong with the web server...

### How to reproduce

Install on Synology Docker.

### Expected behavior

Working application :)

### LinkAce version

latest

### Setup Method

Docker

### Operating System

other (please specify in description)

**Comment by Kovah** [comment]
Hi, please use the simple Docker setup: https://www.linkace.org/docs/v1/setup/setup-with-docker/simple/ for Docker on Synology NAS.

**Comment by Kovah** [comment]
Please open this issue again if you need further help.
