### ISSUE TITLE
Postgresql no unix socket connection

### ISSUE THREAD

**Issue by piegamesde** [Kovah/LinkAce#575]
### Bug Description

It looks like that there is no way to connect to the postgresql server via unix socket. This is important because it allows using peer authentication instead of having to deal with passwords. I found that there is a `DATABASE_URL` environment variable in the configuration but it does not seem to be used (tbh I'm not sure what it exactly does).

### How to reproduce

Set the following environment:

```env
DB_CONNECTION=pgsql
DB_DATABASE=linkace
DATABASE_URL=/run/postgresql
```

`php artisan migrate --force --no-interaction`

### Expected behavior

It works

### Logs

```shell
`SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed`
```

### LinkAce version

1.10.5

### Setup Method

PHP

### Operating System

Linux (Ubuntu, CentOS,...)

**Comment by Kovah** [comment]
You could try to connect to a socket by disabling the default settings for databases in your .env file:
```
DB_HOST=
DB_DATABASE=
DB_USERNAME=
DB_PASSWORD=
```
This is needed because the configuration sets sensible defaults, like `127.0.0.1` as the host. I guess that the underlying framework takes those settings instead of the DATABASE_URL setting. 🤔

**Comment by Kovah** [comment]
Any news on this?

**Comment by piegamesde** [comment]
No, I don't use LinkAce anymore, so I can't try it out.
