### ISSUE TITLE
Could not check updates

### ISSUE THREAD

**Issue by gianter962** [Kovah/LinkAce#576]
### Bug Description

![Schermata a 2022-11-24 11-34-29](https://user-images.githubusercontent.com/77537820/203763178-01fe7508-a49b-4aee-86f4-630bf46f8bc7.png)

### How to reproduce

Just load home page

### Expected behavior

No update needed

### LinkAce version

v1.10.5

### Setup Method

Docker

### Operating System

Linux (Ubuntu, CentOS,...)

**Comment by Kovah** [comment]
`https://updates.linkace.org/api/current-version` works as expected and returns the correct version.

> Resolving timed out

Sounds like a DNS issue. Is the domain blocked on your end or by a corporate firewall?

**Comment by gianter962** [comment]
Now works again ... but i didn't do nothing boohoo  ... thank you for the supersonic answer 
![Schermata a 2022-11-24 18-35-25](https://user-images.githubusercontent.com/77537820/203841326-61c3c6c3-a6d2-46e3-9264-0e5a685ec0d5.png)

**Comment by Kovah** [comment]
Hm... maybe some network hiccup. Feel free to re-open the issue if it happens agein.
