### ISSUE TITLE
Import: imported bookmarks are public by default regardless of settings

### ISSUE THREAD

**Issue by piegamesde** [Kovah/LinkAce#577]
### Bug Description

I just imported a few bookmarks, and while looking at them I noticed the "Check is enabled / Disable check" button, because I'd expect it to be off. This made me look into it some more and I quickly noticed that the bookmark was not set to private, even though this is my default setting for new bookmarks. I double-checked this by enabling guest mode and going into an incognito window, and indeed all imported bookmarks were publicly browsable there.

### How to reproduce

1. Make new bookmarks private by default
2. Import some bookmarks
3. Check their visibility

### Expected behavior

The default setting for new bookmarks should be respected. Additionally, a new option for the import process may be added to control this. I'd also like to see whether or not a bookmark is public or not without having to click on the "Edit" button, i.e. from the link view itself.

### LinkAce version

v1.10.5

### Setup Method

PHP

### Operating System

Linux (Ubuntu, CentOS,...)

### Client details

Arch Linux, Chromium

**Comment by Kovah** [comment]
Thanks for taking the time to report this. Should definitely not happen that way.

**Comment by piegamesde** [comment]
Looking at the code, https://github.com/Kovah/LinkAce/blob/main/app/Actions/ImportHtmlBookmarks.php#L64 I'm not sure what it does but it looks for a `pub` attribute on the imported link? But also maps that value to private (if I understand the code correctly the boolean is flipped). Either way, I guess that the value is missing and thus defaults to false, so maybe have a check for the field and then fall back to the global setting if not present or something like that.

**Comment by Kovah** [comment]
Sounds good, defaulting to the settings is a good idea.
