### ISSUE TITLE
Link Sharing: Toggle All On/Off Toggles Individual States Not All Services

### ISSUE THREAD

**Issue by BrookeDot** [Kovah/LinkAce#581]
### Bug Description

When using the "Toggle all on/off" link when some services are enabled the state of those services changes to "off" with the rest of the services toggling to "on". The expected behavior would be that all services get toggled to the opposite state and if services are already selected (enabled) they are toggled off.

### How to reproduce

1. Go to example.com/settings/system
2. Scroll to "Link Sharing"
3. Enable some sharing services
4. Select "Toggle all on/off"
5. Note that the individual services' state is toggled, not all services

This can also be seen in the demo

### Expected behavior

The expected behavior would be that all services get toggled to the opposite state and if services are already selected (enabled) they are toggled off.

### Screenshots

https://user-images.githubusercontent.com/150348/204404208-02117a84-b25b-4922-81bc-1861591d09b4.mov

### LinkAce version

v1.10.5

### Setup Method

PHP

### Operating System

Linux (Ubuntu, CentOS,...)

**Comment by Kovah** [comment]
Thank you very much for the report. Definitely not working as expected.
