### ISSUE TITLE
Import: imported tags are public by default

### ISSUE THREAD

**Issue by nonmaterialistically** [Kovah/LinkAce#588]
### Bug Description

I was watching the #577 issue because I wanted to import all my bookmarks as private. I updated LinkAce today and it works correctly. I think that the same issue applies to tags too, which wasn't mentioned. In my case the tags were folders from a Chrome bookmark export.

### How to reproduce

1. Make new tags private by default
2. Import some bookmarks that include tags
3. Check the tags

### Expected behavior

The default setting for new tags should be respected

### LinkAce version

v1.11.0

### Setup Method

Docker

### Operating System

Linux (Ubuntu, CentOS,...)

**Comment by Kovah** [comment]
That's a good point, thanks for keeping an eye on this. 👍
