### ISSUE TITLE
MySQL Passwords ending in '#' are not working - leads to ISE 500 errors

### ISSUE THREAD

**Issue by ranasats** [Kovah/LinkAce#596]
Hi,

I tried to setup LinkAce using a generated password for my MariaDB database ending in `#`. Setup guide works up until the last page where you setup your password for the user. After hitting submit at that stage, I would get ISE 500 errors. I went through the laravel logs and found that LinkAce is getting SQL access denied errors, and the password it is trying to use is truncated at the `#`.

Not sure if this is a know bug, but took me a while to figure it out! Hope not many people are having this issue.

Thanks!

**Comment by Kovah** [comment]
Wrap your password in quotes (`"`), otherwise the # is seen as the start of a comment.
