### ISSUE TITLE
Registry "404 Not Found"

### ISSUE THREAD

**Issue by Drallas** [Kovah/LinkAce#606]
### Bug Description

Not sure if this is an Issue or matter for Discussions!?

But my Watchtower log shows:

Could not do a head request for "linkace/linkace:simple", falling back to regular pull.
Reason: registry responded to head request with "404 Not Found", auth: "not present"

I see the tag is available in Docker Hub.

It used to update normal before, and didn't change my configuration.

### How to reproduce

.

### Expected behavior

Normal Docker Pull.

### LinkAce version

v1.11.1

### Setup Method

Docker

### Operating System

Linux (Ubuntu, CentOS,...)

**Comment by Kovah** [comment]
Not sure if this is a local issue, because the tag is definitely there: https://hub.docker.com/layers/linkace/linkace/simple/images/sha256-883225088ecf5fd7da105396ad531cf589a2145551a2a8e7ec6fa0d219e7013b?context=explore

Just tried to pull `linkace/linkace:simple` and worked fine. 🤔

**Comment by Drallas** [comment]
Weird, Pull is fine in my server too.

`docker pull linkace/linkace:simple
simple: Pulling from linkace/linkace
Digest: sha256:8ef9311802f4fb71b2602bf68d0d1e18d342757e7ad13b0e01f539824bdbbe9a
Status: Image is up to date for linkace/linkace:simple
docker.io/linkace/linkace:simple`

Perhaps the Watchtower Container wasn't healthy, restarted it and hope next run is going to be fine.

**Comment by Drallas** [comment]
To add to this.

Without any intervention, resolved itself.

Seemed to have been a DockerHub glitch.
