### ISSUE TITLE
500 Sever error

### ISSUE THREAD

**Issue by magicman32** [Kovah/LinkAce#614]
### Discussed in https://github.com/Kovah/LinkAce/discussions/613

<div type='discussions-op-text'>

<sup>Originally posted by **magicman32** February 18, 2023</sup>
when I run docker compose up -d
it fires up
I goto ip address and error page appears
but when I check .env file the app key is not being generated which Im guessing could be the problem
so on reddit I found the command
docker exec -it linkace_app_1 php artisan key:generate
I execute and tell it yes to proceed, its says it generated an app key
but when I check the .env file its not been written to file

Please advice
can I generate key to be shown and then cut and paste in .env file?</div>

**Comment by Kovah** [comment]
Please keep the discussion in the support forum. Issues are for bugs only.
