### ISSUE TITLE
v1.11.2+ Backup Fails

### ISSUE THREAD

**Issue by jimmybrancaccio** [Kovah/LinkAce#627]
### Bug Description

After updating from v1.11.2 backups are now failing due to `mysqldump` missing. From the email LinkAce sends:

```
Exception message: The dump process failed with a none successful exitcode. Exitcode ======== 127: Command not found Output ====== <no output> Error Output ============ sh: mysqldump: not found
```

I can provide the full output if necessary. I checked the container and `mysqldump` is nowhere to be found:

```console
/app # find / -name mysqldump
/app #
```

### How to reproduce

1. Setup LinkAce using the Docker method.
2. Make sure you have the following set in your `.env` file - be sure to use a valid email address:
    ```
    BACKUP_ENABLED=true
    BACKUP_DISK=s3
    BACKUP_NOTIFICATIONS=true
    BACKUP_NOTIFICATION_EMAIL=me@domain.com
    BACKUP_MAX_SIZE=512
    ```
3. Ensure to [configure the cron](https://www.linkace.org/docs/v1/setup/post-setup/#2-setup-the-cron).
4. Observe when a backup is attempted to be created that an email is received stating the backup failed due to the missing `mysqldump` binary.

### Expected behavior

I expect that the upgrade does not prevent backups from working.

### LinkAce version

v1.11.3

### Setup Method

Docker

### Operating System

Linux (Ubuntu, CentOS,...)

**Comment by Kovah** [comment]
Huh. That's weird. There was nothing removed from the base image. 😳 I'll check what's wrong.
