### ISSUE TITLE
No lists and tags properties in API response

### ISSUE THREAD

**Issue by semelyanov86** [Kovah/LinkAce#629]
### Bug Description

According to documentation, link response consist of following fields:
{
"id": 84,
"user_id": 1,
"url": "https://duckduckgo.com/",
"title": "string",
"description": "string",
"icon": "string",
"is_private": true,
"status": 1,
"check_disabled": true,
"lists": [],
"tags": [],
"created_at": "2020-03-09T19:33:23.000000Z",
"updated_at": "2020-03-09T19:33:23.000000Z",
"deleted_at": "2020-03-09T19:33:23.000000Z"
}
But in fact, there is no lists or tags fields in response

### How to reproduce

1. Send GET to api/v1/links
2. Check that in data[*] there is no links and tags fields

### Expected behavior

Expected to see all fields according to documentation

### LinkAce version

1.11.4

### Setup Method

PHP

### Operating System

Linux (Ubuntu, CentOS,...)

### Client details

Send request vie insomnia

**Comment by Kovah** [comment]
API docs are updated.
