### ISSUE TITLE
Can't import bookmark's file generated from Google Chrome 111 to LinkAce 1.11.4

### ISSUE THREAD

**Issue by welrbraga** [Kovah/LinkAce#630]
### Bug Description

I just installed a instance with LinkAce follow the instructions (https://www.linkace.org/docs/v1/setup/setup-with-docker/advanced/) and everything was ok, but I can't import my bookmarks on it.

### How to reproduce

The bookmark's file (a HTML file) was generated on Google Chrome 111.0.5563.110
Like I said, I've just installed the LinkAce follow instructions in ("Setup with Docker (Advanced)" page)
After finish the setup and create my account, I tried to import the file.

The message error showed is:
`Something went wrong while trying to import the bookmarks. Please consult the application logs.
`

On log application I have this message:
`Integrity constraint violation: 1048 Column 'is_private' cannot be null
`
Details in log attached here (in "Logs" section). Note that I had removed the name and weblink and putting HIDDENLINK, HIDDENNAME on these places.

I've tried many times with privacy options set to "No" and "Yes", but without effect.

I've add manually two links without problems and tried to import bookmarks again, but without success.

### Expected behavior

The expect result was that all my bookmarks were imported but nothing was added.

### Logs

```shell
error	production	2023-03-29 19:00:01	SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'is_private' cannot be null (SQL: insert into `links` (`user_id`, `url`, `title`, `description`, `icon`, `is_private`, `created_at`, `updated_at`) values (1, HIDDENLINK, HIDDENNAME, ?, link, ?, 2022-11-30 11:01:49, 2023-03-29 19:00:01)) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'is_private' cannot be null (SQL: insert into `links` (`user_id`, `url`, `title`, `description`, `icon`, `is_private`, `created_at`, `updated_at`) values (1, HIDDENLINK, HIDDENNAME, ?, link, ?, 2022-11-30 11:01:49, 2023-03-29 19:00:01)) at /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)
debug	production	2023-03-29 19:15:29	[#1531] Header ended: xbs mobile
debug	production	2023-03-29 19:15:29	[#1531] Content: </DL>
info	production	2023-03-29 19:15:29	PARSING LINE #1531
info	production	2023-03-29 19:15:29	File parsing ended
```

### LinkAce version

v1.11.4

### Setup Method

Docker

### Operating System

Linux (Ubuntu, CentOS,...)

### Client details

OS: Linux Ubuntu 20.04
Browser: Google Chrome 111

**Comment by sheckandar** [comment]
Same issue with Firefox bookmarks. Edge bookmarks file generates the same error.

Shaarli export generates the same error as well. 

Bookmarks from any known browsers cannot be imported.

**Comment by welrbraga** [comment]
Hi guys,

I did some more tests here and finally acquive sucessfuly imported the links.

After many tests I noted that the only option needed to be changed to successfully import the links is "Private Tags by default".

This was confirmed with a completly reinstall in a emptyenvironment.

Maybe a simple default value on that field when importing data should solve the problem and future releases.

**Comment by Kovah** [comment]
Thanks for the report. I will have a look at this when I have time. Likely an issue with default options for the privacy setting.
