### ISSUE TITLE
module check during setup fails with PDO missing if only pdo-sqlite is installed

### ISSUE THREAD

**Issue by alexlehm** [Kovah/LinkAce#633]
### Bug Description

I am currently trying to get started with linkace with sqlite (for a first test, i know it is not recommended) and I set up the php modules with apt, however the modules check at the start of setup says that PDO is missing

I have installed pdo-sqlite, so it is definitely available, however it is not detected. After installing mysql and pgsql the check lists PDO as available.

maybe you could change the check to mention which PDO modules are missing, it found it a bit confusing at first since I thought I had a install issue

### How to reproduce

start with a "plain" ubuntu with php8.1 installed (i am using ubuntu 22)

unpack linkace and create the preliminary requirements for the permissions and the modules including php-pdo-sqlite

run host/linkace/public/

the page lists PDO as missing

### Expected behavior

I would expect it to say PDO available but postgres missing (or mysql) and that should be a soft error

### Screenshots

![image](https://user-images.githubusercontent.com/156144/230601380-6241857b-990a-49b0-a43a-cbf39c77934b.png)

### LinkAce version

linkace-v1.11.4

### Setup Method

PHP

### Operating System

Linux (Ubuntu, CentOS,...)

### Client details

Client is Firefox, OS is Ubuntu 22.04.2 LTS

**Comment by alexlehm** [comment]
After trying a few things, I got it working, but I still think a more detailed error would be better (like PDO-mysql is missing)

**Comment by Kovah** [comment]
The thing is that if you are using anything else other than MaySQL, the web setup is not suitable at the moment. I would like to leave it like that until the web setup is really compatible with all databases.
