### ISSUE TITLE
Tags and lists are public by default despite private default setting

### ISSUE THREAD

**Issue by chrissawyerfan4** [Kovah/LinkAce#644]
### Bug Description

Newly created tags and lists can be viewed by guests despite these settings:

```
$ sqlite3 storage/database.sqlite
sqlite> select * from settings where key like '%private_default';
id|user_id|key|value
1|1|links_private_default|1
13|1|notes_private_default|1
14|1|lists_private_default|1
15|1|tags_private_default|1
```

### How to reproduce

0. Log in on https://demo.linkace.org
1. Configure the system to have private lists or tags by default
1. Click the button to create a new link
1. Add a list or tag for this link which does not yet exist in the system
1. Open https://demo.linkace.org/guest/tags or https://demo.linkace.org/guest/lists

### Expected behavior

It respects the setting, or assumes a private default which is less likely to lead to an issue for the user

Presumably this can be fixed here https://github.com/Kovah/LinkAce/blob/main/app/Repositories/TagRepository.php#L20 but I don't know this framework that well to know what function to call to check this setting, and was hoping this might be a 3-minute change for you

### Client details

Verified on demo system running v1.12.0, at least for tags (I assume lists is the same, as I had this issue locally as well)

**Comment by Kovah** [comment]
Hi, thanks for taking your time to report this and even verifying it on the demo setup. Will have a look as soon as possible.

**Comment by chrissawyerfan4** [comment]
Thank you for resolving this! :)
