### ISSUE TITLE
[BUG] Sorting links by random give error of SQLSTATE

### ISSUE THREAD

**Issue by vdbhb59** [Kovah/LinkAce#651]
### Bug Description

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'random' in 'order clause' (SQL: select * from `links` where `user_id` = 1 and `links`.`deleted_at` is null order by `random` asc, RAND() limit 24 offset 0) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'random' in 'order clause' (SQL: select * from `links` where `user_id` = 1 and `links`.`deleted_at` is null order by `random` asc, RAND() limit 24 offset 0) at /PATH_TO/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)

When I try and sort the links by random, I get the above error, and the page give an internal 500 error (see snap). URL bar address: **https://instanceurlhere/links?orderBy=random**

### How to reproduce

Go to All Links
Select Order By > Random
The above error of SQL gets thrown up
The Page throws a 500 internal error and the Logs give the database error.

### Expected behavior

The links should be randomly shown, based on a set of coded parameters and logic.

### Logs

```shell
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'random' in 'order clause' (SQL: select * from `links` where `user_id` = 1 and `links`.`deleted_at` is null order by `random` asc, RAND() limit 24 offset 0) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'random' in 'order clause' (SQL: select * from `links` where `user_id` = 1 and `links`.`deleted_at` is null order by `random` asc, RAND() limit 24 offset 0) at /PATH_TO/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)
```

### Screenshots

![image](https://github.com/Kovah/LinkAce/assets/60728004/c3bc23fe-b780-4054-a705-532a45e5788e)

### LinkAce version

V1.12.0

### Setup Method

PHP

### Operating System

Linux (Ubuntu, CentOS,...)

### Client details

Windows 11 - Librewolf - 113.0.1-1
MX Linux - LibreWolf - 133.0.1-1

**Comment by Kovah** [comment]
Hi, thanks for taking the time to report this issue. It's already know and a solution will be released in the following weeks (see #638).

Closing this as a duplicate for now.
