### ISSUE TITLE
Chrome login

### ISSUE THREAD

**Issue by An7hrax** [Kovah/LinkAce#71]
Hello,
Not sure if it's only me but i setup LinkAce without docker and got everything running.
But I'm not able to login via Chrome, Chrome-android or Bromite.
After logging in the button change color and nothing happens..

It works without any problem on Firefox and Internet Explorer.

**Comment by Kovah** [comment]
Hi, are you using the latest version of LinkAce?
Could you open the [browser console](https://developers.google.com/web/tools/chrome-devtools/#console) while trying to login, and post errors here if they pop up?

**Comment by An7hrax** [comment]
Git cloned the repo so it's running the latest version.

Logs from server:
`
127.2.3.4 - - [01/Oct/2019:08:24:22 +0200] "GET / HTTP/2.0" 302 376 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
127.2.3.4 - - [01/Oct/2019:08:24:22 +0200] "GET /guest/links HTTP/2.0" 200 5276 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
127.2.3.4 - - [01/Oct/2019:08:24:23 +0200] "GET /assets/img/manifest.json HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
127.2.3.4 - - [01/Oct/2019:08:24:41 +0200] "GET /login HTTP/2.0" 200 3685 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
`
Login prompt without logging in.
![login01](https://user-images.githubusercontent.com/2539341/65939369-02e59000-e426-11e9-887b-823ef857ee62.PNG)

After pressing the login button
![login02](https://user-images.githubusercontent.com/2539341/65939370-05e08080-e426-11e9-80c4-3d7e9ff7ccee.PNG)

And the logs from firefox where it is working:
`
127.2.3.4 - - [01/Oct/2019:08:36:37 +0200] "GET /login HTTP/2.0" 200 3683 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"
127.2.3.4 - - [01/Oct/2019:08:36:58 +0200] "POST /login HTTP/2.0" 302 368 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"
127.2.3.4 - - [01/Oct/2019:08:36:58 +0200] "GET /dashboard HTTP/2.0" 200 4321 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"
`

Looks like Post is not getting sent from Chrome when pressing the login button.

**Comment by Kovah** [comment]
Okay, will take a look at it. Maybe caused by the loading button script (#53)

**Comment by Kovah** [comment]
For whatever reason, Chrome did not correctly continues the event propagation after the loading handling, so the underlying form never got submitted. I fixed that, will be available with some other fixes in v0.0.23.
