### ISSUE TITLE
Can't save Wayback Machine links via bookmarklet

### ISSUE THREAD

**Issue by respencer** [Kovah/LinkAce#717]
### Bug Description

When trying to save a webpage in the Wayback Machine using the bookmarklet you get directed to the non-existent archived link of your own bookmarklet/add link.

### How to reproduce

1. Go to: https://web.archive.org/web/20230319211922/https://12factor.net/dependencies
2. Click on your LinkAce bookmarklet.
3. You'll now be directed to: https://web.archive.org/web/20230319211922/https://example.com/bookmarklet/add?u=https%3A%2F%2Fweb.archive.org%2Fweb%2F20230319211922%2Fhttps%3A%2F%2F12factor.net%2Fdependencies&t=The%20Twelve-Factor%20App&d=

### Expected behavior

My own site link was used: https://example.com/bookmarklet/add?u=https%3A%2F%2Fweb.archive.org%2Fweb%2F20230319211922%2Fhttps%3A%2F%2F12factor.net%2Fdependencies&t=The%20Twelve-Factor%20App&d=

### LinkAce version

v1.12.2

### Setup Method

PHP

### Operating System

Linux (Ubuntu, CentOS,...)

### Client details

- OS: IDMS Linux [like Arch Linux]
- Browser: Mozilla Firefox
- Browser Version: 116.0.3 (64-bit)

**Comment by Kovah** [comment]
That's a really odd behaviour. I guess that the Wayback Machine messes with the standard `window.open()` function and alters how it works. Will have a deeper look later on.

**Comment by Kovah** [comment]
I can confirm that the Internet Archive messes with the window.open() function which is definitely not supposed to happen. It's a standard JS function and overriding it with something else is bad practise. At the moment there is no way around saving the URL directly in LinkAce.

**Comment by Kovah** [comment]
Closing this for now. If anybody knows a suitable fix, please post it.
