### ISSUE TITLE
The existing lists and tags won't load in the link edit page (V2.0.0)

### ISSUE THREAD

**Issue by tigerzioo** [Kovah/LinkAce#835]
### Bug Description

It looks good when add a new link. 
When editing an existing link, the existing lists and tags won't load.

### How to reproduce

1. Edit an existing link.
2. The saved lists and tags won't show up.
3. When type a list or tag, the existing lists and tags won't show up either.

### Expected behavior

The saved lists and tags of the link should show up.

### Screenshots

![EditLink](https://github.com/user-attachments/assets/190d7f6f-f573-4c72-b5c0-6badd42514f4)

### LinkAce version

v2.0.0

### Setup Method

Docker

### Operating System

Linux (Ubuntu, CentOS,...)

**Comment by Kovah** [comment]
Thanks for the report! Will have a look soon. Probably just a small thing.

**Comment by Kovah** [comment]
So, I checked this locally. I get the lists and tags as expected:

![](https://github.com/user-attachments/assets/32e0a54e-a622-420c-b4c9-4f3138d2f9ab)

---

There are two things to check here:
- Are there really some lists which you are able to see? Check under Lists.
- Are the lists properly added for the select (even though it doesn't display them)? Inspect the list select in your browser ([example how-to](https://developer.chrome.com/docs/devtools/inspect-mode)), it should look like this: ![](https://github.com/user-attachments/assets/b10adf65-e7ad-4c9a-b041-3eff21f875e7)

**Comment by tigerzioo** [comment]
This is the docker image I am using.
docker pull linkace/linkace:2.x

Here is the source code I can see from the edit page. (Not the link create page, the link create page is fine)
I can see the list I selected when I create the link but it doesn't show. And I don't see any other lists in the source code.
```
<input name="lists" id="lists" type="text" placeholder="Select a List"
                                class="tag-select" data-value="[{&quot;id&quot;:20,&quot;user_id&quot;:1,&quot;name&quot;:&quot;WebServer&quot;,&quot;description&quot;:null,&quot;visibility&quot;:2,&quot;created_at&quot;:&quot;2024-08-09T04:15:19.000000Z&quot;,&quot;updated_at&quot;:&quot;2024-08-09T04:15:38.000000Z&quot;,&quot;deleted_at&quot;:null,&quot;pivot&quot;:{&quot;link_id&quot;:60,&quot;list_id&quot;:20},&quot;user&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Link&quot;}}]"
                                data-allow-creation="true" data-tag-type="lists">
```

**Comment by Kovah** [comment]
Yes, you are right. I was just checking the creation page. The edit page is broken. Will be fixed in a min.

**Comment by Kovah** [comment]
A new Beta for LinkAce 2 will come next week I guess. Hope you can wait until then. :)

**Comment by tigerzioo** [comment]
Thank you. I am looking forward the new v2 beta.
