### ISSUE TITLE
2.0.0 Beta 1 no-docker with sqlite stuck at requirements check page

### ISSUE THREAD

**Issue by vfrex** [Kovah/LinkAce#836]
### Bug Description

After following the "setup without docker" steps here: https://www.linkace.org/docs/v2/setup/setup-with-sqlite/ and bringing up the built-in testing webserver, the page loads: setup/requirements

All requirements are displayed as met except for PDO MySQL and the Continue button is greyed out.

I tried php8 artisan setup:complete, and the browser brings up the LinkAce login page. Login fails with 419 - Page Expired, CSRF Token Mismatch.

### How to reproduce

Note: environment is an opensuse tumbleweed container on Incus  
Note 2: I also needed php8-zip for key:generate and php8-sqlite for migrate, which were not in the list of require extensions.

1. Follow steps 1-4 here: https://www.linkace.org/docs/v2/setup/setup-without-docker/ 
2. Follow without docker steps here: https://www.linkace.org/docs/v2/setup/setup-with-sqlite/
3. Bring up application with web server

### Expected behavior

I would expect the requirement check to ignore the missing MySQL PDO running on an sqlite backend in the .env, and for the web/wizard process to complete the setup process. 

### LinkAce version

v2.0.0 Beta 1

### Setup Method

PHP

### Operating System

Linux (Ubuntu, CentOS,...)

### Client details

Linux, Firefox (Flatpak)

Also tested the login on Linux, Chrome

**Comment by Kovah** [comment]
This sounds weird. However, SQLite gets complete support for the web setup which should solve a lot of headaches. A new beta of v2 will be released this week, you could try again after this.

Also, I noticed the docs for v2 are quite outdated compared to v1.

**Comment by vfrex** [comment]
I tried a docker install of v2 beta today and could not get it running with sqlite, but that might have been a config error on my part. I also tried v2 beta docker with mysql and got the containers up, no errors in the container logs, but couldn't reach the webserver in browser or curl - no port conflicts. Nothing in the logs about caddy running. Will take a closer look at the dockerfiles in the next few days and see if I can figure out why caddy didn't start.

**Comment by Kovah** [comment]
I have not released the new version yet, so it might make sense to wait. Sorry.

**Comment by vfrex** [comment]
No worries and no rush intended. I'll keep an eye out for it.

**Comment by Kovah** [comment]
Beta 2 is out now with the new setup process.

**Comment by vfrex** [comment]
Setup was successful in a non-docker sqlite using Beta 2. I could close this one and create a new issue for Beta 2 issues - let me know what you prefer. I ran into an import issue that I document below.

From CLI:

`In Connection.php line 829:

  SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: links.visibility (Connection: sqlite, SQL: insert into "links" ("user_id", "url", "title", "description", "icon", "visibilit
  y", "created_at", "updated_at") values (1, https://support.mozilla.org/products/firefox, Get Help, ?, link, ?, 2022-07-04 11:42:17, 2024-09-08 08:27:16))`

and 

`In Connection.php line 587:

  SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: links.visibility`

This same html file imports successfully in Linkace V1 Docker with MySQL. I believe it is the first link in the file. I will test with another backend on Beta 2 later.

**Comment by Kovah** [comment]
Thanks, I will have a look at this in a separate ticket.
