### ISSUE TITLE
Unable to access asset files on Subdir setup

### ISSUE THREAD

**Issue by ani-6** [Kovah/LinkAce#838]
### Bug Description

I have linkace on my ubuntu server as subdir setup. Application source code is in (/var/www/html/linkace). Setup looks good and app functionality works as expected but without assets files.
Application works fine if I put assets folder in root directory of the server(/var/www/html/assets)

### How to reproduce

1. Setup linkace as subdirectoy 
2. Visit the login page after setup.

### Expected behavior

It should access assets files form defined folder in app

### Screenshots

![Screenshot 2024-08-21 095114](https://github.com/user-attachments/assets/6cc29e04-f90e-4262-aef6-10a330dd3486)

### LinkAce version

v1.15.2

### Setup Method

PHP

### Operating System

Linux (Ubuntu, CentOS,...)

### Client details

OS:[Ubuntu], Client:[Firefox]

**Comment by Kovah** [comment]
As mentioned in #837, the installation in a subdirectory is not supported yet and I have no plans for adding it at the moment.
