### ISSUE TITLE
Redirect after deleting a link returns to page 1 instead of the current page

### ISSUE THREAD

**Issue by MDeLuise** [Kovah/LinkAce#852]
### Bug Description

When deleting a link from the “All links” section (`/links`), if the user is on a page other than the first (e.g., `/links?page=2`), after deleting a link, the system redirects back to the first page (`/links`). This forces users to manually navigate back to the page they were on before the deletion.

### How to reproduce

1. Navigate to the "All links" section (`/links`).
1. Scroll to a page other than the first, e.g., `/links?page=2`.
1. On the second page, click on "Delete link" within any link card.
1. After deletion, observe that the system redirects back to `/links` (page 1).

### Expected behavior

After deleting a link from any page in the "All links" section, the system should remain on the same page where the deletion occurred. For example, if the link was deleted on `/links?page=2`, the system should redirect back to `/links?page=2` after deletion, maintaining the user's current page context.

### LinkAce version

v1.15.3

### Setup Method

Docker

### Operating System

Linux (Ubuntu, CentOS,...)

**Comment by Kovah** [comment]
Will be fixed in LinkAce v2 coming out soon.
