### ISSUE TITLE
Bug: docker container - update docs

### ISSUE THREAD

**Issue by Lasim** [Kovah/LinkAce#873]
### Bug Description

According to the docs:

https://www.linkace.org/docs/v2/setup/setup-with-docker/

to run LinkAce with docker:

```bash
docker run -p "8080:80" -v "./database.sqlite:/app/database/database.sqlite" linkace/linkace
```

```bash
root@yolo:~# docker run -p "8080:80" -v "./database.sqlite:/app/database/database.sqlite" linkace/linkace
[17-Dec-2024 15:49:13] NOTICE: fpm is running, pid 1
[17-Dec-2024 15:49:13] NOTICE: ready to handle connections
```

```bash
root@yolo:~# netstat -lntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      22179/docker-proxy  
tcp6       0      0 :::8080                 :::*                    LISTEN      22188/docker-proxy  
```

```bash
root@yolo:~# curl -v http://localhost:8080
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.88.1
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

### How to reproduce

1. Go to docs
2. run docker command
3. execute curl

### Expected behavior

200 HTTP status code when curl http://localhost:8080

### LinkAce version

2

### Setup Method

Docker

### Operating System

Linux (Ubuntu, CentOS,...)

### Client details

OS: Debian, Mac

**Comment by Kovah** [comment]
Hi, `https://www.linkace.org/docs/v2/setup/setup-with-docker/` does not work with the current Docker images. Those instructions are for version 2 of LinkAce, which is not released yet. Please use https://www.linkace.org/docs/v1/setup/setup-with-docker/simple/

**Comment by Lasim** [comment]
Thanks! It works for me :)
